<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>part_c – Madhav Kadam</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2b454536a190732ebf2f95c4f11e6530.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-9b097c31a9caec86beae4783e147e129.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-2b454536a190732ebf2f95c4f11e6530.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-B6Z44LN64S"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-B6Z44LN64S', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Madhav Kadam">
<meta property="og:description" content="">
<meta property="og:image" content="https://storage.googleapis.com/deepmind-media/Blog/Genie/genie_thumbnail.jpg">
<meta property="og:site_name" content="Madhav Kadam">
<meta name="twitter:title" content="Madhav Kadam">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://storage.googleapis.com/deepmind-media/Blog/Genie/genie_thumbnail.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Madhav Kadam</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://drive.google.com/file/d/1hnqTi8Y-63If0PUq-HJ09X44cnxxqlXD/view?usp=sharing" target="_blank"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Poems/disclaimer.html"> 
<span class="menu-text">Poems</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../MyBlog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../books.html"> 
<span class="menu-text">Library</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../travel.html"> 
<span class="menu-text">Atlas</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#part-iii-from-pixels-to-action-vlas-world-models-and-a-hands-on-unified-model" id="toc-part-iii-from-pixels-to-action-vlas-world-models-and-a-hands-on-unified-model" class="nav-link active" data-scroll-target="#part-iii-from-pixels-to-action-vlas-world-models-and-a-hands-on-unified-model">Part III — From Pixels to Action: VLAs, World Models, and a Hands-On Unified Model</a>
  <ul class="collapse">
  <li><a href="#chapter-12-vision-language-action-models-how-robots-inherit-web-knowledge" id="toc-chapter-12-vision-language-action-models-how-robots-inherit-web-knowledge" class="nav-link" data-scroll-target="#chapter-12-vision-language-action-models-how-robots-inherit-web-knowledge">Chapter 12 — Vision-Language-Action Models: How Robots Inherit Web Knowledge</a>
  <ul class="collapse">
  <li><a href="#the-robot-data-problem" id="toc-the-robot-data-problem" class="nav-link" data-scroll-target="#the-robot-data-problem">12.1 The robot data problem</a></li>
  <li><a href="#the-basic-vla-recipe-from-rt-2-to-openvla" id="toc-the-basic-vla-recipe-from-rt-2-to-openvla" class="nav-link" data-scroll-target="#the-basic-vla-recipe-from-rt-2-to-openvla">12.2 The basic VLA recipe: from RT-2 to OpenVLA</a></li>
  <li><a href="#action-chunking-and-act" id="toc-action-chunking-and-act" class="nav-link" data-scroll-target="#action-chunking-and-act">12.3 Action chunking and ACT</a></li>
  <li><a href="#pi_0-a-vision-language-action-flow-model" id="toc-pi_0-a-vision-language-action-flow-model" class="nav-link" data-scroll-target="#pi_0-a-vision-language-action-flow-model">12.4 <span class="math inline">\(\pi_0\)</span>: a Vision-Language-Action Flow Model</a></li>
  <li><a href="#the-pi_0-family-evolution" id="toc-the-pi_0-family-evolution" class="nav-link" data-scroll-target="#the-pi_0-family-evolution">12.5 The <span class="math inline">\(\pi_0\)</span> family evolution</a></li>
  <li><a href="#adarmsnorm-and-the-inference-time-hardware-story" id="toc-adarmsnorm-and-the-inference-time-hardware-story" class="nav-link" data-scroll-target="#adarmsnorm-and-the-inference-time-hardware-story">12.6 AdaRMSNorm and the inference-time hardware story</a></li>
  <li><a href="#the-eth-robot-learning-perspective" id="toc-the-eth-robot-learning-perspective" class="nav-link" data-scroll-target="#the-eth-robot-learning-perspective">12.7 The ETH Robot Learning perspective</a></li>
  </ul></li>
  <li><a href="#chapter-13-world-models-machines-that-dream-the-future" id="toc-chapter-13-world-models-machines-that-dream-the-future" class="nav-link" data-scroll-target="#chapter-13-world-models-machines-that-dream-the-future">Chapter 13 — World Models: Machines That Dream the Future</a>
  <ul class="collapse">
  <li><a href="#what-is-a-world-model-really" id="toc-what-is-a-world-model-really" class="nav-link" data-scroll-target="#what-is-a-world-model-really">13.1 What is a world model — really?</a></li>
  <li><a href="#thread-a-learning-to-dream-rl-world-models-19902025" id="toc-thread-a-learning-to-dream-rl-world-models-19902025" class="nav-link" data-scroll-target="#thread-a-learning-to-dream-rl-world-models-19902025">13.2 Thread A — Learning to Dream (RL world models, 1990–2025)</a></li>
  <li><a href="#thread-b-learning-from-watching-20162025" id="toc-thread-b-learning-from-watching-20162025" class="nav-link" data-scroll-target="#thread-b-learning-from-watching-20162025">13.3 Thread B — Learning from Watching (2016–2025)</a></li>
  <li><a href="#the-convergence-20242026" id="toc-the-convergence-20242026" class="nav-link" data-scroll-target="#the-convergence-20242026">13.4 The Convergence (2024–2026)</a></li>
  <li><a href="#jepa-the-contrarian-bet" id="toc-jepa-the-contrarian-bet" class="nav-link" data-scroll-target="#jepa-the-contrarian-bet">13.5 JEPA — The Contrarian Bet</a></li>
  <li><a href="#the-10b-bet-and-the-nvidia-stack" id="toc-the-10b-bet-and-the-nvidia-stack" class="nav-link" data-scroll-target="#the-10b-bet-and-the-nvidia-stack">13.6 The $10B bet and the NVIDIA stack</a></li>
  <li><a href="#reality-check" id="toc-reality-check" class="nav-link" data-scroll-target="#reality-check">13.7 Reality check</a></li>
  </ul></li>
  <li><a href="#chapter-14-bagel-a-hands-on-unified-multimodal-foundation-model" id="toc-chapter-14-bagel-a-hands-on-unified-multimodal-foundation-model" class="nav-link" data-scroll-target="#chapter-14-bagel-a-hands-on-unified-multimodal-foundation-model">Chapter 14 — BAGEL: A Hands-On Unified Multimodal Foundation Model</a>
  <ul class="collapse">
  <li><a href="#why-bagel-is-the-right-case-study" id="toc-why-bagel-is-the-right-case-study" class="nav-link" data-scroll-target="#why-bagel-is-the-right-case-study">14.1 Why BAGEL is the right case study</a></li>
  <li><a href="#architecture-overview-mixture-of-transformer-experts-mot" id="toc-architecture-overview-mixture-of-transformer-experts-mot" class="nav-link" data-scroll-target="#architecture-overview-mixture-of-transformer-experts-mot">14.2 Architecture overview: Mixture-of-Transformer-Experts (MoT)</a></li>
  <li><a href="#the-two-vision-pathways" id="toc-the-two-vision-pathways" class="nav-link" data-scroll-target="#the-two-vision-pathways">14.3 The two vision pathways</a></li>
  <li><a href="#generalised-causal-attention" id="toc-generalised-causal-attention" class="nav-link" data-scroll-target="#generalised-causal-attention">14.4 Generalised Causal Attention</a></li>
  <li><a href="#training-recipe" id="toc-training-recipe" class="nav-link" data-scroll-target="#training-recipe">14.5 Training recipe</a></li>
  <li><a href="#the-data-story" id="toc-the-data-story" class="nav-link" data-scroll-target="#the-data-story">14.6 The data story</a></li>
  <li><a href="#emerging-properties" id="toc-emerging-properties" class="nav-link" data-scroll-target="#emerging-properties">14.7 Emerging properties</a></li>
  <li><a href="#hands-on-running-bagel" id="toc-hands-on-running-bagel" class="nav-link" data-scroll-target="#hands-on-running-bagel">14.8 Hands-on: running BAGEL</a></li>
  <li><a href="#training-bagel" id="toc-training-bagel" class="nav-link" data-scroll-target="#training-bagel">14.9 Training BAGEL</a></li>
  <li><a href="#what-bagel-teaches-us-about-unified-models" id="toc-what-bagel-teaches-us-about-unified-models" class="nav-link" data-scroll-target="#what-bagel-teaches-us-about-unified-models">14.10 What BAGEL teaches us about unified models</a></li>
  </ul></li>
  <li><a href="#chapter-15-putting-it-all-together-a-unified-picture-of-the-modern-ai-stack" id="toc-chapter-15-putting-it-all-together-a-unified-picture-of-the-modern-ai-stack" class="nav-link" data-scroll-target="#chapter-15-putting-it-all-together-a-unified-picture-of-the-modern-ai-stack">Chapter 15 — Putting It All Together: A Unified Picture of the Modern AI Stack</a>
  <ul class="collapse">
  <li><a href="#the-recurring-patterns" id="toc-the-recurring-patterns" class="nav-link" data-scroll-target="#the-recurring-patterns">15.1 The recurring patterns</a></li>
  <li><a href="#the-great-parallel" id="toc-the-great-parallel" class="nav-link" data-scroll-target="#the-great-parallel">15.2 The Great Parallel</a></li>
  <li><a href="#the-big-open-problems" id="toc-the-big-open-problems" class="nav-link" data-scroll-target="#the-big-open-problems">15.3 The big open problems</a></li>
  <li><a href="#what-to-read-next" id="toc-what-to-read-next" class="nav-link" data-scroll-target="#what-to-read-next">15.4 What to read next</a></li>
  <li><a href="#closing-thought" id="toc-closing-thought" class="nav-link" data-scroll-target="#closing-thought">15.5 Closing thought</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="part-iii-from-pixels-to-action-vlas-world-models-and-a-hands-on-unified-model" class="level1">
<h1>Part III — From Pixels to Action: VLAs, World Models, and a Hands-On Unified Model</h1>
<p>The first two parts of this article walked through the two big abstractions that the modern AI stack rests on. Part A built up the transformer, the autoregressive language model, and its multimodal sibling the vision-language model. Part B built up the latent-variable / score-based / flow-matching family that powers nearly every modern image and video generator. Both abstractions are remarkably general and remarkably <em>disembodied</em>: their world is a stream of tokens or a tensor of pixels, and the model is judged by how well it predicts the next chunk of that stream.</p>
<p>This third part takes the disembodied stack and asks the harder question: what does it look like to glue a transformer and a flow model to a <em>body</em>? What changes when the model has to act in the real world, when “next token” becomes “next motor command”, when the only ground truth is whether the laundry got folded or the egg cracked? And — given that we have nowhere near enough robot data to train a foundation model the way GPT-3 was trained — what kind of <em>imagination engine</em> could fill the gap?</p>
<p>Three threads sit at the centre of the answer: Vision-Language-Action models (VLAs), which retrofit a VLM with a body; world models, which let an agent practise inside its own dreams instead of in expensive reality; and unified multimodal foundation models like BAGEL, which dissolve the boundary between “understanding” and “generation” and end up looking suspiciously like the natural backbone for the previous two. We will end with a synthesis that ties everything in this article back together.</p>
<section id="chapter-12-vision-language-action-models-how-robots-inherit-web-knowledge" class="level2">
<h2 class="anchored" data-anchor-id="chapter-12-vision-language-action-models-how-robots-inherit-web-knowledge">Chapter 12 — Vision-Language-Action Models: How Robots Inherit Web Knowledge</h2>
<section id="the-robot-data-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-robot-data-problem">12.1 The robot data problem</h3>
<p>The single biggest reason robotics has lagged behind language and vision is data. GPT-3 trained on roughly 300 billion text tokens. GPT-4 and successors used trillions. Internet-scale image-text pairs are measured in billions. Robot data, by contrast, is collected one teleoperated demonstration at a time, at roughly real-time speed, by a human pilot wearing a glove or pushing a joystick. The most ambitious foundation-model robotics efforts to date — Physical Intelligence’s <span class="math inline">\(\pi_0\)</span> pre-training mixture, NVIDIA’s GR00T datasets, the public Open X-Embodiment collection — top out at around <strong>ten thousand hours</strong> of teleoperation. That is, if you laid all the data end to end, slightly more than a year of wall-clock robot motion. Compared to the lifetime of YouTube, it is rounding error.</p>
<p>The naive prescription “just collect more” hits a hard economic wall. A skilled teleoperator can collect maybe one to two hours of high-quality manipulation data per day, on a robot that costs tens of thousands of dollars, in a lab that costs more. The cost per hour of robot data is roughly three to four orders of magnitude greater than the cost per hour of scraping web video. Worse, that data is narrow: it lives inside whatever fixtures the lab built and uses whatever objects the experimenters happened to put on the table. A model trained only on robot data inherits the same narrowness.</p>
<p>The Vision-Language-Action (VLA) family is the field’s first serious attempt to escape this trap. The recipe is conceptually simple and rests on one bet: most of what a robot needs to do is <em>semantic</em> knowledge that is already encoded by web-scale vision and language pretraining. A model that already understands what a mug is, what “to the left of” means, what “wipe” implies, what hot liquid does when it spills — all of that comes for free from a vision-language model that read the internet. What is left is the relatively small problem of mapping that knowledge into joint angles and gripper widths. The hope is that the latter can be learned from the few thousand hours of teleoperation data that we actually have, while the former is donated by the VLM backbone.</p>
<blockquote class="blockquote">
<p>The VLA bet, restated: a robot that has read the internet is a much better starting point than a robot that has only watched its own hand. The web is a giant pre-training set for <em>embodied</em> cognition that nobody collected with robotics in mind.</p>
</blockquote>
</section>
<section id="the-basic-vla-recipe-from-rt-2-to-openvla" class="level3">
<h3 class="anchored" data-anchor-id="the-basic-vla-recipe-from-rt-2-to-openvla">12.2 The basic VLA recipe: from RT-2 to OpenVLA</h3>
<p>The earliest VLA in the modern sense is Google’s <strong>RT-2</strong> (2023). Its move was almost outrageously simple: take a vision-language model — the kind we built up in Chapter 6 — and pretend that robot actions are just another language. Discretize each component of the action vector (joint deltas, end-effector pose, gripper open/close) into a small number of bins, treat each bin as a token, and append those tokens to the model’s vocabulary. Now training the model to control a robot is identical, mechanically, to fine-tuning it on text: shift the targets, compute cross-entropy, backpropagate.</p>
<p>This recipe inherited two enormous gifts from the VLM literature. First, the model could still parse arbitrary natural-language instructions (“put the chip bag next to the apple”), because that capability was baked into the backbone. Second, all the semantic priors of the backbone — object categories, spatial relations, affordances learned from captions — were available to the action head without any explicit transfer step. RT-2 demonstrated emergent skills: it could be told to pick up “the extinct animal” and grab the toy dinosaur, because the backbone understood the joke and the head could put a hand on the right object.</p>
<p><strong>OpenVLA</strong> (Stanford, 2024) made this approach concrete and open-source. It is a 7B-parameter Llama-2-based VLM, fine-tuned on the Open X-Embodiment dataset (a million-plus episodes pooled from twenty-two robot platforms), with a tokenized action head. For more than a year it served as the de facto open baseline that everyone else compared against. Its checkpoints are still the first thing you <code>git clone</code> when starting a new VLA project.</p>
<p>But the recipe has two corners it cannot easily turn. First, <strong>discrete action tokens are a clumsy representation for continuous, high-frequency motion.</strong> A six-DoF action vector quantized to, say, 256 bins per axis throws away the precision needed for tasks like inserting a USB connector, threading a needle, or maintaining a delicate grasp. The token grid is too coarse, and refining it explodes the vocabulary. Second, <strong>autoregressive decoding caps your control frequency.</strong> Producing a single seven-token action burns a full forward pass; producing a <em>chunk</em> of fifty actions for smooth real-time control burns fifty forward passes. Even with KV caching, you cannot reach 50 Hz on a 7B model and a typical GPU, which is exactly the frequency window dexterous tasks need.</p>
<p>These two limitations are not fatal — RT-2 and OpenVLA do real, useful things — but they motivate the next two ideas: action chunking, and continuous flow-matching action heads.</p>
</section>
<section id="action-chunking-and-act" class="level3">
<h3 class="anchored" data-anchor-id="action-chunking-and-act">12.3 Action chunking and ACT</h3>
<p>Tony Zhao and colleagues’ <strong>Action Chunking with Transformers (ACT)</strong> paper, published alongside the ALOHA bimanual robot in 2023, made an observation that is obvious in hindsight: a teleoperator does not move one joint at a time. A human pilot demonstrating “pick up the cup” produces a continuous trajectory of joint motions over a half-second window. Asking a learned policy to predict only the <em>next</em> action — and then to be called fifty times per second to produce the next, and the next, and the next — is asking it to do something the teacher never did, namely to make a decision under causal-attention pressure without any look-ahead.</p>
<p>ACT changed the prediction target from a single action to a chunk of <span class="math inline">\(H\)</span> actions:</p>
<p><span class="math display">\[
\mathbf{A}_t = [\mathbf{a}_t, \mathbf{a}_{t+1}, \ldots, \mathbf{a}_{t+H-1}].
\]</span></p>
<p>The policy emits the entire window at once. At deployment the controller executes the first action (or first few), then re-plans, then executes again. Even a simple Gaussian or transformer-based head over chunked actions dramatically smooths the resulting motion, dramatically improves recovery from small perturbations, and turns out to be much easier to train from a few hundred demos. ACT became the workhorse policy class for the ALOHA platform, and it is the conceptual foundation that every modern VLA action head builds on. Chunk sizes of <span class="math inline">\(H = 16\)</span> to <span class="math inline">\(H = 100\)</span> are typical; <span class="math inline">\(\pi_0\)</span> uses <span class="math inline">\(H = 50\)</span>.</p>
<blockquote class="blockquote">
<p>Why does chunking work so well? Two reasons. First, it converts a <em>causal</em> prediction problem (every step depends on every earlier step) into a <em>parallel</em> one within the chunk. Second, it lets the model represent multi-modal trajectories explicitly: at a fork — left around the obstacle or right? — the chunked head can put probability mass on both branches, while a step-by-step policy is forced to commit at each tick.</p>
</blockquote>
</section>
<section id="pi_0-a-vision-language-action-flow-model" class="level3">
<h3 class="anchored" data-anchor-id="pi_0-a-vision-language-action-flow-model">12.4 <span class="math inline">\(\pi_0\)</span>: a Vision-Language-Action Flow Model</h3>
<p>Physical Intelligence’s <strong><span class="math inline">\(\pi_0\)</span></strong> (Black et al., October 2024, arXiv:2410.24164) is the model that combines all of the above and is, at the time of writing, the most empirically convincing VLA in production. It is the closest thing the field has to a “GPT-3 moment” for robotics, and the rest of this chapter unpacks it in detail. The paper itself is worth reading end-to-end; what follows is a guided tour of its architectural choices and the reasoning behind them.</p>
<div id="fig-pi0" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pi0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://www.physicalintelligence.company/blog/pi0/pi0-fig3.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pi0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Figure: <span class="math inline">\(\pi_0\)</span> architecture — a PaliGemma VLM backbone (left) plus a small action expert (right), sharing self-attention via a generalised causal mask. The action expert receives the noised action chunk and proprioceptive state and outputs the flow-matching vector field. See PI 2024, Figure 3.
</figcaption>
</figure>
</div>
<section id="architecture-paligemma-a-300m-action-expert" class="level4">
<h4 class="anchored" data-anchor-id="architecture-paligemma-a-300m-action-expert">Architecture: PaliGemma + a 300M action expert</h4>
<p><span class="math inline">\(\pi_0\)</span> starts from <strong>PaliGemma</strong>, a 3-billion-parameter open VLM from Google: a SigLIP vision encoder feeding into a Gemma language transformer, pretrained on web-scale image-text data. PaliGemma was picked partly for size (small enough for real-time inference) and partly for performance, but the framework is in principle agnostic to the backbone.</p>
<p>The novel addition is an <strong>action expert</strong>: a separate 300M-parameter mini-transformer that lives alongside the main backbone and shares its self-attention operation at every layer. Total parameters: 3.3B (3B backbone + 0.3B expert).</p>
<p>The expert is not a separate model. It is a <em>mixture-of-experts-style branch</em>: at each layer, image and text tokens are processed by the backbone’s FFN, while action and proprioceptive-state tokens are processed by the expert’s FFN. The two streams query and attend to each other through a shared multi-head self-attention. The design is directly inspired by Meta’s <strong>Transfusion</strong> paper (Zhou et al., 2024), which trained a single transformer with two losses — cross-entropy on text tokens and flow / diffusion on image tokens. <span class="math inline">\(\pi_0\)</span> generalises this to a <em>third</em> token type — continuous robot actions — and adds the wrinkle of giving it its own FFN weights.</p>
<p>The motivation is empirical and intuitive. Generation and understanding tokens occupy quite different statistical regions of feature space. Forcing the same FFN to be optimal for “what mug am I looking at?” and “what is the right vector field on action space at <span class="math inline">\(\tau = 0.4\)</span>?” is a worse compromise than just paying the parameter cost of a separate expert. We will see the same pattern again in BAGEL (Chapter 14): hard-routed modality experts beat dense or soft-routed alternatives.</p>
</section>
<section id="conditional-flow-matching-for-continuous-actions" class="level4">
<h4 class="anchored" data-anchor-id="conditional-flow-matching-for-continuous-actions">Conditional flow matching for continuous actions</h4>
<p>We derived rectified flow and conditional flow matching in Chapter 10 of Part B; <span class="math inline">\(\pi_0\)</span> uses exactly that machinery, but applied to action chunks rather than to image latents. Let <span class="math inline">\(\mathbf{A}_t\)</span> be the action chunk of length <span class="math inline">\(H = 50\)</span> and let <span class="math inline">\(\mathbf{o}_t = [\mathbf{I}^1_t, \ldots, \mathbf{I}^n_t, \ell_t, \mathbf{q}_t]\)</span> be the observation: <span class="math inline">\(n\)</span> camera images, a language command <span class="math inline">\(\ell_t\)</span>, and proprioceptive joint state <span class="math inline">\(\mathbf{q}_t\)</span>.</p>
<p>The conditional probability path is the simple linear-Gaussian one from Chapter 10:</p>
<p><span class="math display">\[
q(\mathbf{A}_t^\tau \mid \mathbf{A}_t) = \mathcal{N}(\tau \mathbf{A}_t, (1-\tau)\mathbf{I}), \qquad \tau \in [0,1].
\]</span></p>
<p>At <span class="math inline">\(\tau = 0\)</span> we have pure Gaussian noise; at <span class="math inline">\(\tau = 1\)</span> we have the clean action chunk. Concretely the network is trained by sampling <span class="math inline">\(\epsilon \sim \mathcal{N}(\mathbf{0}, \mathbf{I})\)</span>, forming the noisy chunk</p>
<p><span class="math display">\[
\mathbf{A}_t^\tau = \tau \mathbf{A}_t + (1-\tau)\epsilon,
\]</span></p>
<p>and training the network output <span class="math inline">\(v_\theta(\mathbf{A}_t^\tau, \mathbf{o}_t)\)</span> to match the conditional velocity field</p>
<p><span class="math display">\[
u(\mathbf{A}_t^\tau \mid \mathbf{A}_t) = \mathbf{A}_t - \epsilon.
\]</span></p>
<p>The flow matching loss is then exactly the form derived in Chapter 10:</p>
<p><span class="math display">\[
L^\tau(\theta) = \mathbb{E}_{p(\mathbf{A}_t \mid \mathbf{o}_t),\, q(\mathbf{A}_t^\tau \mid \mathbf{A}_t)} \, \big\lVert v_\theta(\mathbf{A}_t^\tau, \mathbf{o}_t) - u(\mathbf{A}_t^\tau \mid \mathbf{A}_t) \big\rVert^2.
\]</span></p>
<p>Two important practical details. First, the action expert uses <em>full bidirectional</em> attention over the action chunk, so all 50 noisy action tokens attend to one another — exactly as in a diffusion transformer over image patches. Second, the flow-matching timestep <span class="math inline">\(\tau\)</span> is not sampled uniformly. <span class="math inline">\(\pi_0\)</span> uses a <strong>shifted beta distribution</strong> that puts more mass on <em>lower</em> <span class="math inline">\(\tau\)</span> — that is, noisier samples. Empirically this matters because, just as in image diffusion, the network is asked to perform much harder denoising at high noise levels, and over-sampling that regime stabilises training.</p>
</section>
<section id="inference-10-euler-steps" class="level4">
<h4 class="anchored" data-anchor-id="inference-10-euler-steps">Inference: 10 Euler steps</h4>
<p>At inference time we integrate the learned vector field from <span class="math inline">\(\tau = 0\)</span> (pure noise) to <span class="math inline">\(\tau = 1\)</span> (clean action chunk) using forward Euler with step size <span class="math inline">\(\delta = 0.1\)</span>:</p>
<p><span class="math display">\[
\mathbf{A}_t^{\tau + \delta} = \mathbf{A}_t^\tau + \delta\, v_\theta(\mathbf{A}_t^\tau, \mathbf{o}_t).
\]</span></p>
<p>Ten steps from <span class="math inline">\(\tau = 0\)</span> to <span class="math inline">\(\tau = 1\)</span>. Each step is a forward pass through the action expert, <em>not</em> through the full 3B backbone — the observation tokens <span class="math inline">\(\mathbf{o}_t\)</span> are encoded once and their attention keys and values are cached. Only the action-side KV cache has to be recomputed per step. The result is a model that produces a fresh chunk of 50 actions in roughly the time of a single VLM inference, which is what lets it close the loop at 50 Hz on dexterous tasks. This is the same KV-caching trick from Chapter 3, transplanted to a flow-matching head.</p>
<blockquote class="blockquote">
<p>Why ten Euler steps and not the 50 typical of image generation? Action chunks are far lower-dimensional than 1024² images, and the velocity field is smoother in proprioceptive coordinates than in pixel coordinates. Empirically, ten steps closes most of the quality gap to a 50-step integration, and the latency budget is unforgiving. This is one of many places where “robotics inherits diffusion, with shorter steps” turns out to work.</p>
</blockquote>
</section>
<section id="cross-embodiment-training" class="level4">
<h4 class="anchored" data-anchor-id="cross-embodiment-training">Cross-embodiment training</h4>
<p>A single VLA model is trained jointly across <strong>seven</strong> distinct robot configurations:</p>
<ul>
<li><strong>UR5e</strong>: single-arm with parallel-jaw gripper, wrist-mounted plus over-the-shoulder cameras, 7-DoF configuration.</li>
<li><strong>Bimanual UR5e</strong>: two UR5e setups, three cameras, 14-DoF.</li>
<li><strong>Franka</strong>: a Panda arm, two cameras, 8-DoF.</li>
<li><strong>Bimanual Trossen</strong> (the ALOHA platform): two 6-DoF ViperX arms, two wrist cameras + base camera, 14-DoF.</li>
<li><strong>Bimanual ARX / AgileX</strong>: two 6-DoF arms with three cameras, 14-DoF.</li>
<li><strong>Mobile Trossen / Mobile ARX</strong>: bimanual on a mobile base (Mobile ALOHA), 16-DoF action space.</li>
<li><strong>Mobile Fibocom</strong>: bimanual on a holonomic base, 17-DoF action space.</li>
</ul>
<p>These have wildly different joint counts and action conventions. The trick is to <strong>zero-pad</strong> everything to a common 18-dimensional configuration vector and a 17-dimensional action vector — slots that don’t apply to a given robot are simply masked out. The model thus learns a single shared policy whose first few output dimensions are interpreted differently depending on the embodiment token. This is exactly the same trick that lets a single language model handle multiple languages: surface differences are absorbed into the input/output projections while the deep structure is shared.</p>
<p>The pre-training mixture sums to roughly 10,000 hours of dexterous manipulation from these seven platforms (collected by Physical Intelligence) plus the public <strong>Open X-Embodiment</strong> corpus (22 additional robots, mostly lower-frequency control). Each task-robot combination is reweighted by <span class="math inline">\(n^{0.43}\)</span> to keep over-represented tasks from drowning out under-represented ones — a recipe borrowed directly from the LLM data-mixing literature.</p>
</section>
<section id="pre-training-then-post-training" class="level4">
<h4 class="anchored" data-anchor-id="pre-training-then-post-training">Pre-training then post-training</h4>
<p>The training recipe is explicitly modelled on the LLM playbook: a broad, noisy, multi-task <strong>pre-training</strong> phase that produces a base model with rough competence at everything, followed by a small, high-quality, task-specific <strong>post-training</strong> phase that polishes a chosen behaviour.</p>
<p>Pre-training data is messy on purpose. It includes recovery behaviours, suboptimal demos, partial failures, and a wide diversity of object configurations. Post-training data is curated: clean demonstrations of the target behaviour at the target competence level. The empirical claim of the <span class="math inline">\(\pi_0\)</span> paper is exactly the one from GPT-style training: <strong>you cannot get the smoothness of post-training from pre-training data alone, and you cannot get the robustness of pre-training from post-training data alone.</strong> A model fine-tuned only on perfect data is brittle; a base model evaluated zero-shot is fluent but unreliable. You need both.</p>
<p>The downstream tasks they demonstrate are surprisingly long-horizon: a single laundry-folding policy fetches clothing from a dryer, dumps it into a hamper, wheels the hamper to a folding table, picks up each garment from an arbitrary crumpled state, smooths it, folds it, and stacks it. Other showcased tasks include bussing a real lunch table with novel objects, assembling a cardboard box from a flat state, packing eggs into a carton, packing a to-go box and closing it with two arms, and unloading a dryer.</p>
</section>
<section id="the-bottom-line-on-pi_0" class="level4">
<h4 class="anchored" data-anchor-id="the-bottom-line-on-pi_0">The bottom line on <span class="math inline">\(\pi_0\)</span></h4>
<p>The paper shows zero-shot <span class="math inline">\(\pi_0\)</span> outperforming OpenVLA and Octo (a diffusion baseline) on every evaluation task by a wide margin, with the fine-tuned version handling 5-to-20-minute multi-stage behaviours that no prior end-to-end policy had completed. The combination that delivers this — VLM backbone + action expert + flow-matching head + action chunking + cross-embodiment data + pre-train/post-train recipe — is the new template, and every subsequent VLA is best understood as a variation on it.</p>
</section>
</section>
<section id="the-pi_0-family-evolution" class="level3">
<h3 class="anchored" data-anchor-id="the-pi_0-family-evolution">12.5 The <span class="math inline">\(\pi_0\)</span> family evolution</h3>
<p><span class="math inline">\(\pi_0\)</span> was not the end of the line. Physical Intelligence has released a steady cadence of follow-ups, and the trajectory shows where the field is heading.</p>
<p><strong><span class="math inline">\(\pi_0\)</span>-FAST</strong> (early 2025) replaces the flow-matching head with a purely autoregressive variant, using a learned action tokenizer called FAST (Frequency-domain Action Sequence Tokenizer). FAST projects each action chunk to the frequency domain (DCT), keeps the low-frequency coefficients, and quantises them with a learned tokenizer. This produces a tiny number of discrete action tokens per chunk that an autoregressive head can predict in a few decoding steps. It is a useful ablation: it shows that you can recover most of <span class="math inline">\(\pi_0\)</span>’s performance with a clever discrete tokenizer, though the flow-matching head still wins on the most dexterous tasks.</p>
<p><strong><span class="math inline">\(\pi_{0.5}\)</span></strong> (Pertsch et al., April 2025, arXiv:2504.16054) is the open-world generalisation milestone. The headline result: the model can be dropped into homes it has never seen, and complete laundry-folding, table-clearing, and bedroom-cleaning tasks with no environment-specific fine-tuning. Architecturally, <span class="math inline">\(\pi_{0.5}\)</span> uses a trick the team calls <strong>knowledge insulation</strong>: when training on new robot data, only a subset of the parameters (the action expert and late layers) are updated, leaving the VLM-internal world knowledge intact. The effect is to prevent catastrophic forgetting of the web-scale priors during the relatively narrow robot-data fine-tune. The release also moved the inference path to a more efficient flow-matching head that, in <code>openpi</code>, runs the dexterous policy at high frequency on a single GPU.</p>
<p><strong><span class="math inline">\(\pi_{0.6}\)</span></strong> (late 2025) is the <strong>self-improvement</strong> release. It adds an RL-style post-training loop where the model proposes its own continuation data (autonomous practice on the target task), and a reward model — itself a fine-tuned VLM — scores the resulting rollouts. Good rollouts are kept and re-added to the post-training pool. This is the robotics analogue of the RLHF/RLAIF pipelines that polish language models into chat assistants: the base model becomes the data-generator for its own refinement.</p>
<p><strong><span class="math inline">\(\pi_{0.7}\)</span></strong> (April 2026) is the most interesting from the point of view of this article, because it is <em>hybrid</em>: it stops being a pure VLA and becomes a VLA wrapped around a small <strong>world model</strong>. To plan a multi-stage task (operate a never-before-seen air fryer, for instance), <span class="math inline">\(\pi_{0.7}\)</span> first synthesises a sequence of <em>sub-goal images</em> — what the scene should look like after step 1, step 2, step 3 — using a lightweight image-generator based on a BAGEL-style backbone (Chapter 14). The VLA then conditions on each sub-goal image as an additional input, executing the immediate manipulation, while the world model generates the next sub-goal. This decomposition lets the system handle objects whose mechanics it has never been trained on, by mixing-and-matching skill fragments from related training experience.</p>
<p>The arc — flow-matching action head <span class="math inline">\(\to\)</span> open-world generalisation <span class="math inline">\(\to\)</span> self-improvement <span class="math inline">\(\to\)</span> world-model-augmented planning — is, almost step for step, the LLM playbook applied to embodied agents: pre-training, alignment, RLHF, and now agentic tool-use, in twelve months instead of six years. We will return to the implications in Chapter 15.</p>
<blockquote class="blockquote">
<p>A small but telling architectural note: every step of this evolution preserves the action expert + flow matching head from the original <span class="math inline">\(\pi_0\)</span>. The continuous-action flow head is sticky in the same way that decoder-only Transformer + cross-entropy is sticky for language. It is the new default.</p>
</blockquote>
</section>
<section id="adarmsnorm-and-the-inference-time-hardware-story" class="level3">
<h3 class="anchored" data-anchor-id="adarmsnorm-and-the-inference-time-hardware-story">12.6 AdaRMSNorm and the inference-time hardware story</h3>
<p>One detail of the action expert deserves a paragraph because it is genuinely unusual and matters for anyone trying to deploy this on edge hardware. The flow-matching head conditions on the integration step <span class="math inline">\(\tau\)</span> — at <span class="math inline">\(\tau = 0.1\)</span> the model is denoising heavily, at <span class="math inline">\(\tau = 0.9\)</span> it is making small refinements — and the standard trick is <strong>adaptive normalisation</strong>: scale and shift the activations of each layer by a function of <span class="math inline">\(\tau\)</span>. Most diffusion transformers (DiTs) use AdaLN, where the LayerNorm gain and bias are predicted from a <span class="math inline">\(\tau\)</span> embedding. The <span class="math inline">\(\pi_0\)</span> action expert uses <strong>AdaRMSNorm</strong>: the same idea but applied to RMSNorm, which is the normalisation Gemma uses internally. The conditioning vector is computed once per chunk and broadcast across all layers and tokens of the expert.</p>
<p>The reason this matters is that AdaRMSNorm is <em>not</em> a standard primitive on most production NPUs. Mainstream inference stacks have heavily optimised paths for vanilla RMSNorm; conditioning the norm parameters per step adds a small but real bottleneck that is often the single largest contributor to action-expert latency once everything else is fused. A SemiEngineering teardown of <span class="math inline">\(\pi_0\)</span>’s inference path noted exactly this — the AdaRMSNorm step is what stops the model from running at full pipeline efficiency on certain edge accelerators, and is one of the reasons NVIDIA’s Blackwell GB200 (with more flexible elementwise paths) ships the action expert faster than nominally-comparable H100 configurations. The lesson is the usual one: small architectural choices made for training stability or quality can become the dominant inference cost on hardware that was not co-designed for them.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Practical note.</strong> If you are trying to port a <span class="math inline">\(\pi_0\)</span>-style model to a constrained-latency target, profile AdaRMSNorm first. The standard solutions are (a) precompute the per-step scale/shift vectors before the chunk and broadcast them through a fused kernel, (b) fold the scale into the next linear layer when possible, and (c) reduce the number of integration steps below ten — you can often get away with six on simpler tasks.</p>
</div>
</div>
</section>
<section id="the-eth-robot-learning-perspective" class="level3">
<h3 class="anchored" data-anchor-id="the-eth-robot-learning-perspective">12.7 The ETH Robot Learning perspective</h3>
<p>It is worth zooming out for a moment. The <span class="math inline">\(\pi_0\)</span> family is the <em>current</em> state of the art in foundation-model robotics, but the underlying questions — how does an agent learn to act in the world? what is the right mix of imitation, planning, and trial-and-error? — predate VLAs by decades and are surveyed beautifully in courses like ETH Zurich’s Robot Learning course (cvg.ethz.ch/lectures/Robot-Learning). A few themes from that course are worth carrying into the next chapter.</p>
<p><strong>Behaviour cloning vs reinforcement learning vs model-predictive control.</strong> Behaviour cloning — train a policy to imitate a demonstrator — is what every VLA in this chapter does. It is data-efficient and stable to train, but it cannot, by construction, exceed the demonstrator. Reinforcement learning frees you from that ceiling at the cost of exploration: the agent has to <em>try</em> things and be rewarded for them. Model-predictive control is a third paradigm: learn a <em>model</em> of the dynamics, and at runtime, plan in that model by simulating candidate action sequences and picking the best one. Each of the three is the natural fit for different problems, and a recurring theme of modern foundation-model robotics is that real systems blend all three: imitation for the bulk of the policy, RL for the last mile, and (increasingly) a learned world model for the planning loop.</p>
<p><strong>The sim-to-real gap and domain randomisation.</strong> Simulation is essentially free, real-world data is essentially not. So the field spends enormous effort training in simulators (Isaac Gym, Mujoco, RoboCasa, Genesis) and <em>transferring</em> to reality. The historical recipe — domain randomisation, where the simulator’s friction coefficients, lighting, textures, and so on are randomised at training time to force the policy to be invariant to them — works but is brittle, and the harder the manipulation task the wider the gap. World models, as we will see, offer a different solution: instead of training in a hand-engineered simulator, train in a learned one that was distilled from real video.</p>
<p><strong>The ALOHA shrimp sauté.</strong> The single best illustration of where the field actually is sits in the famous ALOHA cooking demos: a bimanual robot, fine-tuned on roughly fifty demonstrations, sautés shrimp to roughly 90% success. It is impressive — and it is also per-dish. Switching to chicken requires another fifty demos. This is the data-vs-generalisation tension that motivates everything that follows. If you want a robot that can cook <em>anything</em>, you cannot collect fifty demos per dish. You need a model whose priors are deep enough that a few examples teach it the new geometry of the new dish; or you need a model that can simulate the new dish itself and practise inside its own head. That second path is what world models are for.</p>
</section>
</section>
<section id="chapter-13-world-models-machines-that-dream-the-future" class="level2">
<h2 class="anchored" data-anchor-id="chapter-13-world-models-machines-that-dream-the-future">Chapter 13 — World Models: Machines That Dream the Future</h2>
<p>The premise of this chapter, which is the longest in Part C, is that the natural complement to a VLA is a <strong>world model</strong>: a learned generative model of how the physical world evolves in response to actions, dense enough that the agent can practise inside it. A world model is what closes the loop between the few thousand hours of robot data we <em>have</em> and the millions of hours of human video we <em>could</em> use. It is also, increasingly, the single most contested concept in machine learning — the term is now used for things that share nothing structurally, and a substantial chunk of the current $10B robotics-AI funding wave is denominated in claims about world models. So we need to be careful.</p>
<section id="what-is-a-world-model-really" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-world-model-really">13.1 What is a world model — really?</h3>
<p>Almost every paper in the past two years has called itself, at some point, a world model. Most of them are not, in any useful sense. Xun Huang (who co-authored the AR-DiT and Self Forcing papers that we will meet shortly) proposed a sharp definition that has since become standard: a world model is a generator with <strong>five properties</strong> — two binary, three on a spectrum.</p>
<p>The two hard constraints:</p>
<ol type="1">
<li><strong>Causal.</strong> Time flows forward only. The model produces frame <span class="math inline">\(t+1\)</span> conditioned on frames <span class="math inline">\(\le t\)</span>, <em>without</em> peeking at frames <span class="math inline">\(&gt; t\)</span>. A bidirectional video generator that “fills in” a clip is not a world model — it cannot be queried on-line.</li>
<li><strong>Interactive.</strong> The model accepts an action at each step and produces the corresponding next state. Without action conditioning, the model is a video player, not a simulator.</li>
</ol>
<p>The three spectrum properties:</p>
<ol start="3" type="1">
<li><strong>Persistent.</strong> It maintains consistency over long horizons. Most current models last seconds before the dream drifts; Genie 3 reaches minutes; nothing reaches hours.</li>
<li><strong>Real-time.</strong> Inference is fast enough that an agent can close the loop. The state of the art is 10–30 FPS.</li>
<li><strong>Physically accurate.</strong> It respects real physics — gravity, friction, deformation, occlusion. The hardest property to satisfy and the most contested in evaluation.</li>
</ol>
<p>By this definition, Sora is <em>not</em> a world model: it is bidirectional, so it fails property 1, and it does not accept actions, so it fails property 2. It is a stunning <em>video generator</em>, and one of the most important models of the decade, but it is structurally incapable of supporting an interactive control loop. The same is true of Veo, Make-A-Video, Imagen Video, and every other bidirectional T2V model. They are imagination engines, not simulators.</p>
<p>The world models that <em>do</em> satisfy properties 1 and 2 — Dreamer, Genie 2 and 3, GameNGen, Oasis, DreamDojo, V-JEPA 2, Cosmos — come from two long-separated traditions that converged around 2024–2025. We need to walk through both.</p>
</section>
<section id="thread-a-learning-to-dream-rl-world-models-19902025" class="level3">
<h3 class="anchored" data-anchor-id="thread-a-learning-to-dream-rl-world-models-19902025">13.2 Thread A — Learning to Dream (RL world models, 1990–2025)</h3>
<p>The world-models-for-RL tradition is, by deep-learning standards, ancient. The idea that an agent should carry an internal generative model of its environment, and plan by querying that model, goes back at least to <strong>Kenneth Craik’s 1943 book <em>The Nature of Explanation</em></strong>, which argued humans “carry small-scale models of reality in their heads”. <strong>Jürgen Schmidhuber</strong> formalised it in 1990 in a technical report titled <em>Making the World Differentiable</em>: an intelligent agent should learn a differentiable forward model of its environment, then train its policy by backpropagating through that model. The idea sat largely dormant for nearly three decades, because the models we knew how to train were not good enough.</p>
<p>The modern era began in 2018, with <strong>David Ha and Schmidhuber’s “World Models” paper</strong> (NeurIPS 2018, accompanied by the lovely worldmodels.github.io demo page). The architecture was almost shockingly small: a VAE that compressed each pixel observation into a 32-dimensional latent vector, an MDN-RNN (a recurrent network with a mixture-density head) that modelled the <em>dynamics</em> in that 32-dim space, and a tiny linear-Gaussian controller trained entirely on <strong>imagined</strong> rollouts inside the MDN-RNN. The agent dreamed; the dream was small; the agent trained itself in the dream; and then when deployed into Car Racing and VizDoom, it worked.</p>
<p>This was proof of concept. The dreams were abstract, the games were toy, the controller had a few thousand parameters. But the core loop — <em>imagine, train, deploy</em> — was right.</p>
<p><strong>Danijar Hafner</strong> spent the following six years building this idea out at scale. His <strong>PlaNet</strong> (2019) introduced the <strong>Recurrent State Space Model (RSSM)</strong>, which split the latent state into a deterministic memory and a stochastic posterior — solving a longstanding representation problem (purely stochastic latents are hard to train, purely deterministic latents cannot model uncertainty). PlaNet learned a world model and used it for <strong>online MPC</strong> on continuous control tasks (Cheetah, Walker), planning by sampling action sequences and rolling them through the world model in latent space.</p>
<p>The <strong>Dreamer</strong> series followed:</p>
<ul>
<li><strong>DreamerV1</strong> (ICLR 2020) trained an actor-critic policy <em>inside</em> the RSSM dream, eliminating the need for online planning. It matched the best model-free RL methods on continuous control while needing far fewer environment samples.</li>
<li><strong>DreamerV2</strong> (ICLR 2021) replaced the continuous latent with a categorical one, scaled up, and hit human-level performance on the Atari benchmark — the first model-based agent to do so.</li>
<li><strong>DreamerV3</strong> (Nature, 2025) used a <em>single</em> set of hyperparameters across 150+ tasks, including the famously hard Minecraft diamond-collection challenge, which it solved from scratch without any task-specific tuning. This was the moment the Dreamer architecture went from “research curiosity” to “general-purpose RL substrate”.</li>
<li><strong>DreamerV4</strong> (Sep 2025) replaced the recurrent backbone with a transformer, scaling cleanly and running roughly 25× faster than V3 by parallelising sequence updates.</li>
</ul>
<p>The most physically resonant moment in this lineage is <strong>DayDreamer</strong> (2022), which put a Dreamer agent on a real quadruped robot. Starting from random initialisation, the robot learned to walk in <strong>one hour</strong> of real-world interaction, because the world model was generating thousands of imagined practice runs between each real attempt. The data efficiency improvement over model-free RL was an order of magnitude.</p>
<p>A different branch of the same tree is DeepMind’s <strong>MuZero</strong> (Schrittwieser et al., Nature 2020). MuZero learns a world model too — but its world model only predicts <em>what matters for decisions</em>: the reward, the value, and the policy. It never reconstructs the observation. This is a more austere philosophy than Dreamer’s: model what you need to plan, and nothing else. MuZero mastered Go, chess, shogi, and Atari with the same code; it is the spiritual ancestor of approaches like JEPA (later in this chapter), which also refuse to reconstruct pixels.</p>
<p>What this tradition got right: the <em>idea</em> of dreaming. Learn dynamics. Imagine futures. Train a policy in the dream rather than in the world. Action conditioning is first-class. Sample efficiency is dramatic.</p>
<p>What it could not do: generalise across environments. A Dreamer agent could reach human-level performance on one Atari game, but it had to be retrained from scratch on the next one. The models were small (tens of millions of parameters), the dreams were abstract vectors no human could inspect, and they required thousands of task-specific episodes. The idea was right. The scale was wrong.</p>
<div id="fig-dreamer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dreamer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://danijar.com/asset/dreamerv3/header.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dreamer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Figure: Dreamer architecture — RSSM with deterministic recurrent state <span class="math inline">\(h_t\)</span> plus stochastic latent <span class="math inline">\(z_t\)</span>; a decoder reconstructs observations as a training signal; the actor and critic train entirely on rollouts in latent space (the “dream”). See Hafner et al., DreamerV3.
</figcaption>
</figure>
</div>
</section>
<section id="thread-b-learning-from-watching-20162025" class="level3">
<h3 class="anchored" data-anchor-id="thread-b-learning-from-watching-20162025">13.3 Thread B — Learning from Watching (2016–2025)</h3>
<p>The parallel thread was learning physical knowledge from <em>video</em>. This was a much more disorganised research programme, but with three reasonably crisp stages.</p>
<p><strong>Stage 1: Video prediction for planning (2016–2018).</strong> Junhyuk Oh’s 2015 paper learned action-conditioned next-frame prediction in Atari; Chelsea Finn’s 2016 work at Berkeley applied the same idea to a real robot arm pushing objects on a table. The plan-by-imagining strategy was simple: predict the camera image after each candidate action, pick the action whose predicted future looked most like your goal. It worked for trivial pushing tasks but degraded fast — predictions blurred within a few frames, and the model could not capture contact dynamics or multimodal outcomes.</p>
<p><strong>Stage 2: Representation learning from human video (2020–2022).</strong> The insight that broke the deadlock was that you do not need a perfect video predictor — you just need an <em>encoder</em> whose latent space is useful for robot policies. <strong>R3M</strong> (Nair et al., 2022) was the breakthrough: train a visual encoder on <strong>Ego4D</strong>, the FAIR egocentric dataset (thousands of hours of cooking, cleaning, manipulation), with a contrastive plus time-contrastive loss. The resulting encoder mapped a single camera image to a 2048-d vector that captured object identity, pose, and grasp-relevant features while ignoring lighting and texture. A Franka arm using R3M features learned manipulation tasks from just <strong>20 demonstrations</strong> — a tenth of what was previously needed. This was the first compelling demonstration that human video could be a <em>substrate</em> for robot learning.</p>
<p>OpenAI’s <strong>VPT</strong> (Video PreTraining, 2022) pushed the same idea further. They trained on <strong>70,000 hours of Minecraft YouTube</strong> with an <em>inverse dynamics</em> model (predict the action between two consecutive frames) and then fine-tuned the resulting policy on a small set of human demonstrations. The model could craft diamond tools from raw Minecraft initialisation — a behaviour the policy had never been explicitly demonstrated. This was the first time internet-scale video pre-training produced a <em>capable agent</em> for a complex sequential task.</p>
<p><strong>EgoMimic</strong> (Kareer et al., ICRA 2025) went one step further: instead of using human video for representation learning, it treated egocentric human footage as direct demonstration data, co-training a unified policy on both robot teleop and human ego-video. Human-embodiment data boosted task performance by 34–228% over robot-only training, and the policy generalised to new objects and scenes.</p>
<p><strong>Stage 3: Video generation at scale (2022–2024).</strong> With the rise of diffusion video models — Make-A-Video (Meta, 2022), Imagen Video (Google, 2022), and the spectacular OpenAI <strong>Sora</strong> in February 2024 — the field finally had high-fidelity generative video that could be conditioned on text. Sora was framed by OpenAI as a <em>world simulator</em>, and the demo reels showed convincing physical phenomena: objects fell, light scattered, hands gripped, cloth wrinkled. Google’s Veo followed with competitive quality.</p>
<p>But, again, Sora was not a world model in Huang’s sense. It used bidirectional attention. It generated whole clips at a time. It did not accept actions. It was a movie engine, not a simulator. You could prompt it to produce a clip of a cat jumping off a couch; you could not <em>control</em> the cat mid-flight.</p>
<p>What this thread contributed: photorealistic generation at scale, evidence that internet-scale video contains transferable physical knowledge, and the engineering infrastructure (video DiTs, tokenisers, training pipelines) to scale a generator to billions of parameters. What it could not do, on its own: close the action loop.</p>
</section>
<section id="the-convergence-20242026" class="level3">
<h3 class="anchored" data-anchor-id="the-convergence-20242026">13.4 The Convergence (2024–2026)</h3>
<p>What the two threads needed from each other is now obvious in retrospect. The RL tradition had action conditioning, online interactivity, and the dream-and-train recipe, but tiny models trained per-task. The video tradition had pre-training scale, photorealism, and rich visual diversity, but no closed loop. A handful of papers between 2024 and 2026 stitched the two together.</p>
<p><strong>Genie</strong> (DeepMind, 2024–2025) introduced the <strong>latent action model</strong> trick. Given two consecutive video frames, train an encoder to compress “what changed” into a small latent vector, and a decoder to render the second frame given the first plus the latent. The latent is, by construction, a learned action representation — even though no human ever labelled actions. With this, you can train an <em>interactive</em> generator on a corpus of plain unlabelled video, then expose the latent action channel as the user-facing control. Genie 1 (Feb 2024) was 160 × 90 at 1 FPS; Genie 2 (Dec 2024) was photorealistic 720p with 10–60 seconds of consistency; Genie 3 (Aug 2025) is 24 FPS at 720p with minutes of consistency. It costs roughly <strong>$100 per hour</strong> to serve.</p>
<div id="fig-genie" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-genie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://storage.googleapis.com/deepmind-media/Blog/Genie/genie_thumbnail.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-genie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Figure: Genie schematic — paired-frame encoder produces a latent action; conditional generator predicts the next frame from prior frames + latent action. Latent actions are learned without labels, then exposed as the user control surface. See Bruce et al., 2024.
</figcaption>
</figure>
</div>
<p><strong>UniSim</strong> (Sherry Yang et al., ICLR 2024 Outstanding Paper) went the other direction: train a <em>single</em> big video diffusion world model jointly on robot and human and simulation video, then train an RL policy <em>entirely inside</em> the world model, and transfer to a real robot. The reported zero-shot pick-and-place success on a real robot was <strong>81%</strong>. This was the first strong demonstration that policies could be born inside a learned video simulator.</p>
<p><strong>AR-DiT / CausVid</strong> (Yin, Huang et al., CVPR 2025) finally made high-quality video diffusion <em>causal</em> and <em>autoregressive</em>. They modified the bidirectional DiT attention to a triangular mask, retrained, and showed that you could produce one frame at a time without quality collapse. This was the structural prerequisite for interactivity — it unlocked properties 1 and 2 simultaneously.</p>
<p><strong>Self Forcing</strong> (Huang et al., NeurIPS 2025) made it <em>real-time</em>. By distilling a 35-step denoising trajectory down to 4 steps using a teacher-student scheme and a careful schedule of student-forcing during training, Self Forcing turned the AR-DiT generator into a 24-FPS interactive video engine. This is the moment the two threads truly converged: causal + interactive + persistent + real-time, all at once.</p>
<p><strong>DreamGen</strong> (NVIDIA, May 2025) was the first practical robotics payoff. The recipe: take a small amount of real robot footage from the robot’s own cameras (including wrist-mounted views), fine-tune a video generation model on it, then prompt the model with language (“pick up the green block”) to <em>generate</em> synthetic robot videos of tasks the robot has never been demonstrated on. Run an inverse dynamics model on the synthetic video to recover the implied joint commands, and add the (synthetic_video, recovered_actions) pairs to the training pool. From a single teleoperation demonstration, a humanoid learned <strong>22 new behaviours</strong> in unseen environments. The video world model became a teleop force multiplier.</p>
<p><strong>DreamDojo</strong> (NVIDIA, Feb 2026) is the apotheosis of the line so far. Pretrained on <strong>44,711 hours of human egocentric video</strong>, action-conditioned through a learned latent action space, distilled to real-time via Self Forcing — the result is a generalist video world model that can evaluate robot policies with a Pearson correlation of <strong>r = 0.995</strong> to actual real-world success rates. That last statistic is the killer one: it means you can rank 20 candidate policies inside DreamDojo and the ranking will match the real world almost exactly. The world model has become a <em>unit-test environment</em> for robot behaviour. This is the first robotics use case in which world models clearly beat alternatives in production.</p>
<p><strong>DreamZero</strong> (NVIDIA, Feb 2026), released alongside DreamDojo, predicts video <em>and</em> motor actions jointly in a single forward pass, reporting roughly 2× generalisation over VLA baselines on unseen tasks. It is one paper, from the team that built it, with no independent replication yet, so it is a directional signal rather than a finished result.</p>
<p>Elsewhere in the convergence: <strong>GameNGen</strong> (Valevski et al., 2024) ran DOOM on a neural net at 20 FPS, demonstrating that a learned model could function as a full game engine. <strong>Decart’s Oasis</strong> is a playable Minecraft-like world generated by a single video world model — try it at oasis2.decart.ai. <strong>Wayve’s GAIA</strong> ($1.2B Series D as of 2025) is the leading AV-simulation world model, used in production for stress-testing self-driving policies.</p>
<blockquote class="blockquote">
<p>The state of the world-models field in mid-2026 is best summarised as: the technical breakthroughs of 2024–2025 (causal AR video DiTs, Self Forcing, latent action models, large-scale ego video pretraining) have moved world models from <em>theoretical primitives</em> to <em>production tools</em> — though only for narrow use cases. Policy evaluation works. AV scenario synthesis works. Game generation works. General manipulation via dreaming still does not.</p>
</blockquote>
</section>
<section id="jepa-the-contrarian-bet" class="level3">
<h3 class="anchored" data-anchor-id="jepa-the-contrarian-bet">13.5 JEPA — The Contrarian Bet</h3>
<p>Not everyone is convinced that the right object to predict is <em>pixels</em>. Yann LeCun has argued for years that pixel prediction is fundamentally wasteful: most pixel-level detail (texture, lighting, noise) is irrelevant to understanding dynamics, and a model that spends its capacity reconstructing this detail is spending capacity in the wrong place. The proposed alternative is the <strong>Joint-Embedding Predictive Architecture (JEPA)</strong>: predict in <em>embedding</em> space instead of pixel space, and never decode at all.</p>
<p>The setup, from the 2022 LeCun position paper <em>A Path Towards Autonomous Machine Intelligence</em> and the I-JEPA paper (Assran et al., FAIR 2023):</p>
<ul>
<li>A <strong>context encoder</strong> <span class="math inline">\(f_\theta\)</span> maps the visible part of an input <span class="math inline">\(x\)</span> to a context embedding <span class="math inline">\(s_x\)</span>.</li>
<li>A <strong>target encoder</strong> <span class="math inline">\(f_\phi\)</span> maps the held-out part <span class="math inline">\(y\)</span> to a target embedding <span class="math inline">\(s_y\)</span>.</li>
<li>A <strong>predictor</strong> <span class="math inline">\(g_\psi\)</span> takes <span class="math inline">\(s_x\)</span> and a positional token describing where <span class="math inline">\(y\)</span> lives, and outputs a prediction <span class="math inline">\(\hat s_y\)</span>.</li>
</ul>
<p>The loss is a simple regression in embedding space with a stop-gradient on the target:</p>
<p><span class="math display">\[
\mathcal{L}_{\text{JEPA}}(\theta, \psi) = \big\lVert g_\psi(f_\theta(x), p_y) - \operatorname{sg}\big(f_\phi(y)\big) \big\rVert^2.
\]</span></p>
<p>The reason this is interesting is that the encoders are <em>free to throw away</em> anything that is unpredictable or irrelevant. Pixel reconstruction punishes the model for forgetting any detail; JEPA does not. If a feature is not predictable from the context, the encoder can quietly drop it. Equivalently, in LeCun’s older energy-based framing: the model assigns low energy when the predicted and target embeddings agree, and the encoder is free to organise its latent space however makes that prediction easy.</p>
<div id="fig-jepa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-jepa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://ai.meta.com/static-resources/ijepa-arch.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-jepa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Figure: JEPA template — context encoder <span class="math inline">\(f_\theta\)</span>, target encoder <span class="math inline">\(f_\phi\)</span> updated by EMA from the context encoder, predictor <span class="math inline">\(g_\psi\)</span> producing <span class="math inline">\(\hat s_y\)</span> from <span class="math inline">\(s_x\)</span> and a position token. The stop-gradient sits on the target side. See I-JEPA, Figure 2.
</figcaption>
</figure>
</div>
<section id="the-collapse-problem-and-its-standard-fix" class="level4">
<h4 class="anchored" data-anchor-id="the-collapse-problem-and-its-standard-fix">The collapse problem and its standard fix</h4>
<p>There is one obvious failure mode. If both encoders are trained jointly to minimise the loss, the trivial solution is for both to map every input to the same constant — loss zero, representations useless. This is <strong>representation collapse</strong>, and avoiding it is the central training problem of every JEPA-style method.</p>
<p>The standard fix has three pieces, and the JEPA literature inherited it almost verbatim from <strong>BYOL</strong> (Grill et al., 2020):</p>
<ol type="1">
<li><strong>Stop-gradient on the target encoder.</strong> The target encoder is treated as a fixed target within each training step; no gradient flows back through it.</li>
<li><strong>EMA update of the target encoder.</strong> Instead of training the target encoder by gradient descent, its weights are updated as an exponential moving average of the context encoder’s weights: <span class="math display">\[\phi \leftarrow m\phi + (1-m)\theta, \qquad m \in [0.996,\, 1.0).\]</span> The momentum coefficient <span class="math inline">\(m\)</span> is typically scheduled up over training.</li>
<li><strong>Asymmetric predictor.</strong> The predictor <span class="math inline">\(g_\psi\)</span> is intentionally smaller / less expressive than the encoders. If it were too powerful, it would short-circuit learning by memorising trivial mappings.</li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> jepa_step(x, y, pos_y,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>              context_enc, target_enc, predictor,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>              opt, m<span class="op">=</span><span class="fl">0.996</span>):</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    s_x      <span class="op">=</span> context_enc(x)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    s_y_pred <span class="op">=</span> predictor(s_x, pos_y)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>        s_y <span class="op">=</span> target_enc(y)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> F.smooth_l1_loss(s_y_pred, s_y)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    opt.zero_grad()<span class="op">;</span> loss.backward()<span class="op">;</span> opt.step()</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> pt, ps <span class="kw">in</span> <span class="bu">zip</span>(target_enc.parameters(),</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                          context_enc.parameters()):</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>            pt.data.mul_(m).add_(ps.data, alpha<span class="op">=</span><span class="dv">1</span> <span class="op">-</span> m)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> loss.item()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This combination is empirically robust but not a <em>guarantee</em>: subsequent analysis (Sobal et al., TMLR 2025) showed that even with EMA and stop-gradient, dimension-wise collapse is possible if masking or predictor capacity is chosen poorly. Some variants add <strong>VICReg-style</strong> variance and covariance regularisers as a safety net.</p>
</section>
<section id="i-jepa-the-first-vision-instantiation" class="level4">
<h4 class="anchored" data-anchor-id="i-jepa-the-first-vision-instantiation">I-JEPA — the first vision instantiation</h4>
<p><strong>I-JEPA</strong> (Assran et al., 2023) instantiated this template for images. Both encoders are Vision Transformers on 16 × 16 patches; the predictor is a narrower ViT of similar depth. The masking strategy is the crucial bit: sample <strong>4 target blocks</strong> each covering 15–20% of the image area, plus <strong>one large context block</strong> covering 85–100% of the image with the target blocks removed. The target blocks are <em>semantic-scale</em>, not single patches, which means the predictor must reason about object structure rather than local texture continuity.</p>
<p>The empirical payoff is large. On ImageNet linear-probe, I-JEPA with ViT-H/14 matches or beats MAE (the leading pixel-reconstruction self-supervised method) using <strong>2–3× less wall-clock compute</strong>. The intuition is clean: predicting in latent space is cheaper than reconstructing 16 × 16 × 3 = 768 pixel values per patch.</p>
</section>
<section id="v-jepa-extension-to-video" class="level4">
<h4 class="anchored" data-anchor-id="v-jepa-extension-to-video">V-JEPA — extension to video</h4>
<p><strong>V-JEPA</strong> (Bardes et al., 2024) extended the recipe to video. A clip is tokenised into a 3D grid of (height × width × time) patches, and the encoder processes this as one long sequence. The critical design choice is masking: prior video models like VideoMAE used <strong>tube masking</strong>, where the same spatial region is masked across all temporal frames. Tube masking is a shortcut, because filling in one frame fills in all the others — the scene rarely changes that fast. V-JEPA instead uses <strong>3D block masking</strong>: random rectangular blocks in the spatiotemporal volume, with limited temporal extent. The result forces the model to reason about <em>motion and scene dynamics</em>, not just static appearance.</p>
<p>V-JEPA showed state-of-the-art results on motion-heavy benchmarks (Something-Something v2) and on action-anticipation tasks (Epic-Kitchens-100). But it was action-free: it learned what <em>tends</em> to happen, not what happens <em>given an action</em>. Closing that gap is what V-JEPA 2 is about.</p>
</section>
<section id="v-jepa-2-a-world-model-on-real-robots" class="level4">
<h4 class="anchored" data-anchor-id="v-jepa-2-a-world-model-on-real-robots">V-JEPA 2 — a world model on real robots</h4>
<p><strong>V-JEPA 2</strong> (Assran et al., June 2025, arXiv:2506.09985) is the model that turns the JEPA template into a real-world predictive controller. The recipe is two-stage and is the cleanest demonstration so far that latent-space world models can drive a real robot zero-shot.</p>
<p><strong>Stage 1: action-free pretraining.</strong> Train a ViT-g/16 (≈ 1B parameters) encoder + a predictor on <strong>1M+ hours of internet video plus 1M images</strong>, with 16-second 64-frame inputs and the V-JEPA 3D block masking. Standard JEPA loss, no actions. After this stage V-JEPA 2 hits state-of-the-art on Epic-Kitchens-100 action anticipation, and, when paired with an 8B LLM as a visual encoder, scores <strong>84.0 on PerceptionTest</strong> and <strong>76.9 on TempCompass</strong> for video question answering. The encoder alone has become a reusable video foundation model.</p>
<div id="fig-vjepa2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vjepa2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://scontent-iad3-1.xx.fbcdn.net/v/t39.2365-6/vjepa2_diagram.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vjepa2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Figure: V-JEPA 2 two-stage recipe — Stage 1 trains a ViT-g/16 encoder + predictor on 1M+ hours of internet video with the standard JEPA latent-prediction loss; Stage 2 freezes the encoder and trains a small action-conditioned predictor on 62 hours of robot data, used at deployment time inside a CEM planning loop. See Assran et al., 2025.
</figcaption>
</figure>
</div>
<p><strong>Stage 2: action-conditioned post-training (V-JEPA 2-AC).</strong> Freeze the encoder. Train a fresh <strong>300M autoregressive transformer predictor</strong> on a tiny corpus — about <strong>62 hours of unlabelled robot interaction video</strong> from the public DROID dataset, augmented with action and proprioception. The predictor now takes the current latent state <span class="math inline">\(z_t\)</span>, an action vector <span class="math inline">\(a_t\)</span>, and a proprioceptive signal, and outputs the predicted next latent <span class="math inline">\(\hat z_{t+1}\)</span>. Two losses are used: a teacher-forcing next-step loss and a two-step rollout loss that discourages compounding errors.</p>
<p>Deployment is where this gets interesting. V-JEPA 2-AC is run <strong>zero-shot</strong> on Franka Emika Panda arms in <em>two labs that do not appear in DROID training data</em>, with goals specified as image targets. At inference time, a <strong>Cross-Entropy-Method (CEM)</strong> planning loop samples action sequences, rolls each one through the world model in latent space, and re-fits the action distribution to the elites:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> vjepa2_ac_planning(current_obs, goal_image,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                       encoder, predictor,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                       action_horizon<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                       n_samples<span class="op">=</span><span class="dv">512</span>, n_iters<span class="op">=</span><span class="dv">3</span>, top_k<span class="op">=</span><span class="dv">64</span>):</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    z_current <span class="op">=</span> encoder(current_obs)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    z_goal    <span class="op">=</span> encoder(goal_image)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    mu  <span class="op">=</span> torch.zeros(action_horizon, action_dim)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    std <span class="op">=</span> torch.ones(action_horizon, action_dim)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> it <span class="kw">in</span> <span class="bu">range</span>(n_iters):</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        actions <span class="op">=</span> sample_actions(mu, std, n_samples)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        z <span class="op">=</span> z_current.unsqueeze(<span class="dv">0</span>).expand(n_samples, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(action_horizon):</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>            z <span class="op">=</span> predictor(z, actions[:, t], proprio_t)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> <span class="op">-</span>((z <span class="op">-</span> z_goal) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        elite_idx <span class="op">=</span> scores.topk(k<span class="op">=</span>top_k).indices</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        mu  <span class="op">=</span> actions[elite_idx].mean(dim<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        std <span class="op">=</span> actions[elite_idx].std(dim<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> mu[<span class="dv">0</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Reported pick-and-place success on <strong>novel objects in novel environments</strong> is in the 65–80% range. And here is the punchline: planning is roughly <strong>30× faster</strong> than a comparable Cosmos-based pixel-prediction alternative, because all the candidate rollouts happen in 1024-dimensional latent space — no decoder is invoked. You do not have to <em>render</em> the future to evaluate it.</p>
<blockquote class="blockquote">
<p>This is the cleanest statement of the JEPA bet: for <em>planning and control</em>, generation is wasted compute. The agent only needs to predict the <em>representation</em> of the future. Whether that bet wins long-term against pixel-space world models like DreamDojo is, as of this writing, the open empirical question of the field.</p>
</blockquote>
</section>
<section id="the-variant-zoo-and-lejepa" class="level4">
<h4 class="anchored" data-anchor-id="the-variant-zoo-and-lejepa">The variant zoo and LeJEPA</h4>
<p>The JEPA template has been ported to many modalities:</p>
<ul>
<li><strong>A-JEPA</strong> (audio, 2023) — on mel-spectrograms with a curriculum masking strategy. Interestingly, random patch masking beats block masking for audio.</li>
<li><strong>MC-JEPA</strong> — joint optical-flow and content prediction in a multi-task variant.</li>
<li><strong>Point-JEPA</strong> and <strong>3D-JEPA</strong> — adapt the template to point clouds, with patches as small groups of 3D points.</li>
<li><strong>Graph-JEPA</strong> — subgraph patches with hyperbolic target projections.</li>
<li><strong>VL-JEPA</strong> (Dec 2025) — predict the continuous embeddings of held-out text rather than autoregressively decoding text tokens, with the actual decoder only invoked when text output is needed. Reports stronger performance with ~50% fewer trainable parameters.</li>
</ul>
<p>The most consequential recent development is <strong>LeJEPA</strong> (Balestriero &amp; LeCun, Nov 2025). The paper proves a striking theoretical result: under reasonable assumptions, the optimal embedding distribution for downstream prediction risk is <strong>isotropic Gaussian</strong>. They then introduce <strong>SIGReg</strong> — Sketched Isotropic Gaussian Regularisation — which uses random one-dimensional projections of the embeddings and a univariate normality test (built on the Cramér-Wold principle) to enforce isotropic Gaussianity in linear time and memory. The full LeJEPA objective is the standard JEPA prediction loss plus SIGReg, and the entire collapse-prevention machinery (EMA, stop-grad, asymmetric predictor, VICReg) can be replaced by <strong>one regulariser, in roughly 50 lines of code</strong>, with theoretical justification. Reported empirical results are competitive on standard benchmarks. If LeJEPA scales, three years of careful heuristic engineering will have been replaced by a clean theoretical principle. Worth watching.</p>
</section>
<section id="open-problems-with-jepa" class="level4">
<h4 class="anchored" data-anchor-id="open-problems-with-jepa">Open problems with JEPA</h4>
<p>A few honest concerns from practitioners (and from the Fadaeinejad review of the family):</p>
<ul>
<li><strong>The JEPA loss is a poor proxy for representation quality.</strong> Loss can be low while representations are degenerate. Practitioners rely on downstream linear-probe or attentive-probe accuracy as the true signal, which makes hyperparameter search expensive.</li>
<li><strong>The training recipe is brittle.</strong> Mask scale, mask count, EMA schedule, predictor depth, and target normalisation all interact in unstable ways. Multiple failure modes (full collapse, dimension collapse, mean-learning) can hide behind a normal-looking loss curve.</li>
<li><strong>Scaling laws are unclear.</strong> Pixel-based video diffusion has well-understood scaling behaviour. JEPA does not yet. V-JEPA 2 is encouraging at 1B params and 1M+ hours, but we lack a clean curve.</li>
<li><strong>Action conditioning is the bottleneck.</strong> V-JEPA 2 pragmatically separates action-free pretraining from action-conditioned post-training, but this means the action representation only sees ~62 hours of robot data. The pretraining videos contain millions of human actions implicitly — but they are not labelled with action vectors. Learning action-aware representations directly from internet video is the most important open problem in this space, and it is exactly the problem the Genie latent-action approach attacks from a different angle.</li>
<li><strong>Pixel-space and latent-space world models may be complementary, not competitive.</strong> A hybrid — predict latents fast for planning, generate pixels slow for visualisation or as a sim-to-real teacher signal — is a natural next architecture and is likely the next milestone.</li>
</ul>
</section>
</section>
<section id="the-10b-bet-and-the-nvidia-stack" class="level3">
<h3 class="anchored" data-anchor-id="the-10b-bet-and-the-nvidia-stack">13.6 The $10B bet and the NVIDIA stack</h3>
<p>It is worth pausing on the capital landscape, because it tells you something the papers do not: where the industry actually believes the value is.</p>
<p>Over $10B has been invested in world-model and robotics-AI companies in the past 18 months. The money sits in four layers:</p>
<ul>
<li><strong>Pure world-model companies</strong> building the simulator itself: AMI Labs ($1.03B, LeCun), World Labs ($1.23B), Runway ($860M+), Rhoda ($450M), Decart ($153M), Embo ($100M+).</li>
<li><strong>Robot foundation-model companies</strong> that use world models as one component: Physical Intelligence ($1.1B+), Skild ($1.83B), Figure ($2B+), Mind Robotics ($615M).</li>
<li><strong>Platforms</strong> that build and open-source the stack: NVIDIA, Google DeepMind.</li>
<li><strong>Big tech pivots</strong>: OpenAI’s post-Sora robotics turn, Tesla, xAI.</li>
</ul>
<p>The interesting pattern is that companies <em>using</em> world models have raised more than companies <em>building</em> them. Either the world-model layer is structurally underfunded, or the largest robotics companies will build this capability in-house — and indeed 1X Technologies has already done so.</p>
<p><strong>The NVIDIA stack</strong> is the strategic event in the space. NVIDIA has open-sourced (Apache 2.0) an entire physical-AI pipeline: <strong>Cosmos Predict 2.5</strong> (14B-parameter video foundation model, 200M video clips), <strong>DreamDojo</strong> (44K hours, r=0.995 policy eval), <strong>DreamZero</strong> (joint video + action prediction), <strong>EgoScale</strong> (the scaling law: R² = 0.9983 between human-video hours and robot performance), and the productised <strong>GR00T N2</strong> robot brain. The strategic logic is straightforward and not new: it is CUDA for physical AI. Give away the software, sell the hardware. DreamZero runs at 7 Hz on Blackwell GB200 and not in real time on H100. If every robotics company builds on this stack, they all need Blackwell.</p>
<p>For pure-world-model startups this is existential. DreamDojo is free and trained on 44,711 hours of video. “We built a world model” is no longer a moat. Differentiation has to come from somewhere else: proprietary domain data NVIDIA does not have, vertical integration into a product the model is one component of, faster inference, or — as AMI Labs is betting — a <em>fundamentally different architecture</em> (JEPA, predicting in latent space rather than pixel space).</p>
<p>Jim Fan, who runs NVIDIA’s GEAR Lab, has named the broader pattern <strong>The Great Parallel</strong>. Robotics is following the LLM playbook step by step. World models are the pretraining stage — learn to simulate the next physical state the way GPT learned to predict the next token. VLA fine-tuning collapses the pretraining onto the thin slice that matters for real robots. RL / preference optimisation carries the last mile. The same three-step recipe that took LLMs from GPT-3 to o1 in six years. If the parallel holds, the systems we have today — robots that learn to walk in an hour, world models you can navigate through, predictions correlated at r=0.995 with reality — are the <strong>GPT-2 of physical AI</strong>. None of them existed three years ago.</p>
</section>
<section id="reality-check" class="level3">
<h3 class="anchored" data-anchor-id="reality-check">13.7 Reality check</h3>
<p>That capital should not be mistaken for a finished product. Almost everything still on the field’s wishlist is unsolved:</p>
<ul>
<li><strong>General household manipulation.</strong> No robot reliably operates an unmodified home. Best-case demos (ALOHA shrimp sauté, <span class="math inline">\(\pi_{0.5}\)</span> home cleaning) are still per-task and per-environment, with high variance.</li>
<li><strong>Contact-rich dexterous tasks.</strong> Threading needles, inserting connectors, sliding cards into wallets — anything where forces matter as much as positions — remains hard for both VLAs and world models, in large part because both classes of model are <em>vision-only</em>. Touch, force feedback, and proprioception are second-class citizens.</li>
<li><strong>Transfer.</strong> Cross-embodiment, cross-environment, and cross-task generalisation are reported but rarely demonstrated robustly. The open robot datasets (Open X-Embodiment in particular) have known quality and diversity issues. Pristine simulation benchmarks have approached saturation while real-world zero-shot performance lags far behind.</li>
<li><strong>Action conditioning from internet video.</strong> No current method extracts action labels from raw web video at the quality needed to train a generalist policy. Genie’s latent action model is the most promising direction so far, but the resulting action space is opaque and hard to align with the action conventions of any particular robot.</li>
<li><strong>Long-horizon planning.</strong> Even the best world models lose coherence within seconds-to-minutes. Multi-stage tasks (<span class="math inline">\(\pi_{0.7}\)</span>’s “operate a never-seen air fryer”) still require explicit subgoal decomposition by a separate planner.</li>
</ul>
<p>The honest framing is the one in the Moe Capital essay this chapter has been tracking: <em>robotics AI as a whole is earlier than $10B in funding suggests.</em> The pieces are now in place. The bet that dreaming about the world matters for the hardest manipulation problems is reasonable. The timeline is uncertain. But to borrow Jim Fan’s line: a generation born too late to explore the Earth and too early to explore the stars may have arrived just in time to teach machines how to dream the physical world into existence.</p>
</section>
</section>
<section id="chapter-14-bagel-a-hands-on-unified-multimodal-foundation-model" class="level2">
<h2 class="anchored" data-anchor-id="chapter-14-bagel-a-hands-on-unified-multimodal-foundation-model">Chapter 14 — BAGEL: A Hands-On Unified Multimodal Foundation Model</h2>
<p>We have spent the last two chapters describing systems whose source code is mostly closed and whose weights are mostly inaccessible. The closing chapter of this technical tour is deliberately the opposite: a model you can download, run, fine-tune, and study tonight. <strong>BAGEL</strong> (Deng, Zhu, Li et al., ByteDance Seed, May 2025, arXiv:2505.14683) is the most important <em>open</em> unified multimodal foundation model of the year. It is the model that quietly shows up under the hood of <span class="math inline">\(\pi_{0.7}\)</span>. It is the model you can clone right now and play with. And it is the cleanest illustration of the architectural lessons of this entire article.</p>
<section id="why-bagel-is-the-right-case-study" class="level3">
<h3 class="anchored" data-anchor-id="why-bagel-is-the-right-case-study">14.1 Why BAGEL is the right case study</h3>
<p>The reasons to spend a chapter on BAGEL specifically:</p>
<ul>
<li><strong>It is open</strong>, Apache 2.0, with public weights and a public training recipe.</li>
<li><strong>It is unified</strong>: a single model handles vision-language understanding (read a chart, answer a question, identify an object) <em>and</em> visual generation (text-to-image, image editing, video frame prediction, 3D manipulation, world navigation).</li>
<li><strong>It is the right size</strong>: 7B <em>active</em> parameters / 14B total, runnable on a single 32 GB GPU (or 12 GB with NF4 quantization).</li>
<li><strong>It is on the frontier of both axes</strong>: matches Qwen2.5-VL on understanding benchmarks, matches SD3 / FLUX.1-dev on generation.</li>
<li><strong>It shows the architecture pattern we have seen everywhere</strong>: hard-routed modality experts sharing self-attention. The same pattern as <span class="math inline">\(\pi_0\)</span>’s action expert.</li>
<li><strong>It actually appears as a component of frontier systems</strong>: <span class="math inline">\(\pi_{0.7}\)</span> uses a BAGEL-derived backbone as its world model for sub-goal generation.</li>
</ul>
<p>So studying BAGEL is studying the modern open architecture in one place.</p>
<div id="fig-bagel" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bagel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="https://github.com/ByteDance-Seed/Bagel/raw/main/assets/qualitative.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bagel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Figure: BAGEL architecture — Mixture-of-Transformer-Experts. One understanding expert handles text + ViT tokens, one generation expert handles VAE tokens, both share self-attention at every layer. See BAGEL paper, Figure 2.
</figcaption>
</figure>
</div>
</section>
<section id="architecture-overview-mixture-of-transformer-experts-mot" class="level3">
<h3 class="anchored" data-anchor-id="architecture-overview-mixture-of-transformer-experts-mot">14.2 Architecture overview: Mixture-of-Transformer-Experts (MoT)</h3>
<p>BAGEL is a decoder-only transformer initialised from <strong>Qwen2.5</strong> (RMSNorm, SwiGLU, RoPE, Grouped-Query Attention, plus added QK-Norm for training stability). The novel part is the <strong>MoT</strong> structure: every Qwen layer is duplicated into two parallel copies (the <em>understanding expert</em> and the <em>generation expert</em>), each with its own attention projections and FFN, but with the two streams <strong>sharing self-attention</strong> at every layer. This is the same architectural family as <span class="math inline">\(\pi_0\)</span>’s action expert + VLM backbone, generalised: now we have two experts instead of one expert + backbone, and the second expert is the size of the first.</p>
<p>The paper ablates this against two cleaner alternatives:</p>
<ul>
<li><strong>Dense</strong>: a single Qwen body handles both modalities.</li>
<li><strong>MoE</strong>: duplicate only the FFNs, share the attention.</li>
<li><strong>MoT</strong>: duplicate <em>everything</em> — attention projections and FFNs — and share only the attention operation itself.</li>
</ul>
<p>On a controlled 1.5B-parameter sweep, MoT wins decisively, with the gap most pronounced on the generation MSE loss. The interpretation is the same one we kept seeing: jointly optimising the same parameters for two very different objectives steers the model toward a worse compromise region of weight space. <em>Decoupling</em> the experts at the parameter level, but <em>coupling</em> them at the attention level, is the right trade-off. Hard routing wins.</p>
<p>Importantly, MoT and MoE have the same training and inference FLOPs as the dense baseline, because only one expert’s parameters are activated per token (text/ViT tokens use the understanding expert; VAE tokens use the generation expert). The cost is in parameter count (≈ 2× the dense baseline), not compute.</p>
</section>
<section id="the-two-vision-pathways" class="level3">
<h3 class="anchored" data-anchor-id="the-two-vision-pathways">14.3 The two vision pathways</h3>
<p>A unified model needs to <em>see</em> in two different modes. When it is doing visual understanding (answering “how many books are on the table?”) it needs semantic representations. When it is doing visual generation (text-to-image) it needs low-level reversible representations. BAGEL bites the bullet and ships two encoders:</p>
<ul>
<li><strong>Understanding pathway: SigLIP2-so400m/14.</strong> Initialised from the public SigLIP2 checkpoint at 384 × 384 resolution, then position embeddings interpolated and <strong>NaViT</strong> integrated so the model can process images at <em>native aspect ratios</em> up to 980 × 980. A two-layer MLP connector matches feature dimensions to the Qwen hidden state.</li>
<li><strong>Generation pathway: FLUX VAE.</strong> The frozen VAE from FLUX.1 — 8× spatial downsample, 16-channel latent — followed by a 2 × 2 patch embedding to halve the token count again and match Qwen’s hidden size. The VAE is never trained.</li>
</ul>
<p>Both pathways use <strong>2D positional encoding</strong> before the tokens enter the LLM. For the generation expert, the diffusion <em>timestep</em> — which conditional flow we are currently solving — is added directly to the initial hidden state of the VAE tokens. This is a deliberate departure from the AdaLN convention of DiTs, which conditions on the timestep by predicting per-layer scale and shift. BAGEL just dumps the timestep embedding into the residual stream once. The paper calls this “cleaner”; in practice it removes the AdaLN bottleneck and saves both parameters and inference latency. (Contrast with <span class="math inline">\(\pi_0\)</span>, where AdaRMSNorm <em>is</em> used in the action expert and is a known inference bottleneck — different design point, different trade-off.)</p>
</section>
<section id="generalised-causal-attention" class="level3">
<h3 class="anchored" data-anchor-id="generalised-causal-attention">14.4 Generalised Causal Attention</h3>
<p>A single training sample for BAGEL can contain text, multiple input images (as ViT tokens <em>and</em> clean VAE tokens for conditioning), a target image (as noised VAE tokens for the flow-matching MSE loss), and more text afterward. Naive attention masking does not work: we need text tokens to be causal among themselves but bidirectional over visual splits, we need clean VAE tokens to be cached and re-used across decoding, and we need <em>noised</em> VAE tokens to never leak back into the prefix.</p>
<p>The solution is <strong>generalised causal attention</strong>: partition each sample into modality splits, and apply different attention rules inside vs across splits.</p>
<ul>
<li><strong>Across splits.</strong> Tokens in split <span class="math inline">\(k\)</span> may attend to all tokens in splits <span class="math inline">\(j &lt; k\)</span> (causal between splits).</li>
<li><strong>Inside text splits.</strong> Causal attention as usual.</li>
<li><strong>Inside visual splits.</strong> Bidirectional attention — all visual tokens in a split see each other, exactly as in a DiT or ViT.</li>
<li><strong>Noised VAE tokens.</strong> These exist only to feed the rectified-flow MSE loss. Subsequent tokens (whether image, ViT, or text) do <em>not</em> attend back to them. After the image is generated, the noised tokens are replaced in the KV cache by their clean counterparts.</li>
</ul>
<p>The result is implemented in PyTorch with <strong>FlexAttention</strong>, which yields roughly a <strong>2× speedup</strong> over naive scaled-dot-product attention with manual masks. During inference, the structure lets BAGEL cache (clean VAE, ViT) KV pairs and reuse them as the rest of the sequence is decoded — exactly the KV-cache trick from Chapter 3 that we saw in <span class="math inline">\(\pi_0\)</span>.</p>
<p>For classifier-free guidance during interleaved inference, BAGEL drops text / ViT / clean VAE tokens at training time with probabilities (0.1, 0.5, 0.1), so the model learns to handle all the unconditional variants.</p>
</section>
<section id="training-recipe" class="level3">
<h3 class="anchored" data-anchor-id="training-recipe">14.5 Training recipe</h3>
<p>BAGEL is trained in <strong>four stages</strong>, summarised in Table 3 of the paper:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 54%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>Stage</th>
<th>Tokens</th>
<th>LR</th>
<th>What is trained</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Alignment</td>
<td>4.9 B</td>
<td><span class="math inline">\(1 \times 10^{-3}\)</span></td>
<td>Only the MLP connector</td>
<td>Vision encoder &amp; LLM frozen; image-captioning data only</td>
</tr>
<tr class="even">
<td>Pre-training</td>
<td>2.5 T</td>
<td><span class="math inline">\(1 \times 10^{-4}\)</span></td>
<td>Everything except VAE</td>
<td>Add QK-Norm. Native resolution. 2.5T tokens of mixed data</td>
</tr>
<tr class="odd">
<td>Continued Training</td>
<td>2.6 T</td>
<td><span class="math inline">\(1 \times 10^{-4}\)</span></td>
<td>Everything except VAE</td>
<td>Higher resolution. Bump diffusion timestep shift 1.0 → 4.0. Up the interleaved data fraction</td>
</tr>
<tr class="even">
<td>SFT</td>
<td>72.7 B</td>
<td><span class="math inline">\(2.5 \times 10^{-5}\)</span></td>
<td>Everything except VAE</td>
<td>Curated subset; switch EMA ratio 0.9999 → 0.995</td>
</tr>
</tbody>
</table>
<p>Loss weighting is <strong>CE : MSE = 0.25 : 1</strong>. The cross-entropy (text) and MSE (generation) losses behave oppositely as a function of learning rate — bigger LR makes MSE converge faster, smaller LR helps CE. The weighting reconciles them. The learning rate is <em>constant</em> after warmup, not cosine-decayed, so that training can be resumed cleanly when new data arrives without restarting. AdamW with <span class="math inline">\(\beta_1 = 0.9\)</span>, <span class="math inline">\(\beta_2 = 0.95\)</span>, and <strong><span class="math inline">\(\epsilon = 10^{-15}\)</span></strong> — that small <span class="math inline">\(\epsilon\)</span> is a Llama-3 trick for suppressing loss spikes in long training runs.</p>
</section>
<section id="the-data-story" class="level3">
<h3 class="anchored" data-anchor-id="the-data-story">14.6 The data story</h3>
<p>The training corpus is the actual main contribution of BAGEL — perhaps even more than the architecture. It is the first time anyone published the full recipe for a <em>trillion-token interleaved multimodal corpus</em>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 22%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: right;"># samples (M)</th>
<th style="text-align: right;"># tokens (T)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Text only</td>
<td style="text-align: right;">400</td>
<td style="text-align: right;">0.4</td>
</tr>
<tr class="even">
<td>Image-Text pairs (VLM, understanding)</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td>Image-Text pairs (T2I, generation)</td>
<td style="text-align: right;">1,600</td>
<td style="text-align: right;">2.6</td>
</tr>
<tr class="even">
<td><strong>Interleaved understanding</strong></td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td><strong>Interleaved generation: video</strong></td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0.7</td>
</tr>
<tr class="even">
<td><strong>Interleaved generation: web</strong></td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.4</td>
</tr>
</tbody>
</table>
<p>The grey rows are the contribution: large-scale interleaved sequences in which text and images alternate naturally. Video interleaved is built by extracting frames from filtered Koala36M and MVImgNet2.0 video, captioning the inter-frame changes with a distilled Qwen2.5-VL-7B captioner (cap at 30 tokens to suppress hallucination), and serialising as <code>[frame_1, caption_1, frame_2, caption_2, ...]</code>. Web interleaved is built on OmniCorpus (Common Crawl-derived), filtered by a two-stage fastText + LLM classifier, with a <em>caption-first</em> serialisation: insert a Qwen2.5-VL-generated caption <em>before</em> each image to give the model a localised target before generation.</p>
<p>On top of this, BAGEL adds <strong>500K reasoning-augmented examples</strong> — DeepSeek-R1-style chains of thought paired with T2I, free-form editing, and conceptual editing tasks. These are the data behind BAGEL’s most striking emergent behaviour, <em>thinking before drawing</em>.</p>
</section>
<section id="emerging-properties" class="level3">
<h3 class="anchored" data-anchor-id="emerging-properties">14.7 Emerging properties</h3>
<p>The central scientific result of the BAGEL paper is <strong>emergence</strong>, in the strict Wei-et-al-2022 sense. The team logged performance on four task families as a function of training tokens (the famous Figure 7):</p>
<ul>
<li><strong>Image understanding</strong> (mean across MME-S, MMBench, MMMU, MM-Vet, MathVista, MMVP) saturates earliest — 85% of peak performance is reached at roughly <strong>0.18T tokens</strong>.</li>
<li><strong>Image generation</strong> (GenEval) saturates next — 85% at roughly <strong>0.68T tokens</strong>.</li>
<li><strong>Conventional image editing</strong> (GEdit-Bench) takes longer — 85% at roughly <strong>2.64T tokens</strong>.</li>
<li><strong>“Intelligent” editing</strong> (IntelligentBench — the team’s new benchmark for free-form edits requiring real multimodal reasoning) takes longest — 85% at roughly <strong>3.61T tokens</strong>, with the score <em>tripling</em> from ~15 to ~45 between 3T and 4.5T tokens.</li>
</ul>
<p>The pattern is exactly the one Wei et al.&nbsp;described for LLMs: distinct atomic skills saturate independently, and the <strong>compositional</strong> skill that combines them emerges <em>after</em> the atomic ones are in place. Basic understanding emerges first. Basic generation emerges next. Editing — which requires both — emerges later. Intelligent editing — which requires understanding, generation, <em>and</em> reasoning across modalities — emerges latest. This is a clean experimental confirmation in the multimodal setting of the LLM emergence story we built up in Chapter 4.</p>
<p>The paper also reports a striking ablation: <strong>removing the ViT tokens</strong> (so the generation expert only sees the VAE latent of the input) costs 16 points on IntelligentBench but barely moves classical editing scores. The visual <em>semantics</em> — what the ViT pathway provides — are required for reasoning-driven edits, not for pixel-local ones. This is the architectural justification for keeping both vision pathways even though they are partially redundant.</p>
</section>
<section id="hands-on-running-bagel" class="level3">
<h3 class="anchored" data-anchor-id="hands-on-running-bagel">14.8 Hands-on: running BAGEL</h3>
<p>Now the practical part. The minimum recipe to get BAGEL running on a single GPU:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/bytedance-seed/BAGEL.git</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> BAGEL</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> create <span class="at">-n</span> bagel python=3.10 <span class="at">-y</span> <span class="kw">&amp;&amp;</span> <span class="ex">conda</span> activate bagel</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install <span class="at">-r</span> requirements.txt</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install flash_attn==2.5.8 <span class="at">--no-build-isolation</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>flash_attn</code> install line is the one most likely to bite you — it builds from source against your local CUDA toolkit, and a mismatch between PyTorch’s bundled CUDA and your system CUDA is a common failure. If the pre-built wheel is available for your CUDA version, prefer that.</p>
<p>Next, download the checkpoint. The README uses <code>huggingface_hub.snapshot_download</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> huggingface_hub <span class="im">import</span> snapshot_download</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>snapshot_download(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    repo_id<span class="op">=</span><span class="st">"ByteDance-Seed/BAGEL-7B-MoT"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    local_dir<span class="op">=</span><span class="st">"./checkpoints/BAGEL-7B-MoT"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    local_dir_use_symlinks<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The full checkpoint is roughly 28 GB on disk. Plan storage accordingly.</p>
<p>Then launch the Gradio UI:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> app.py                  <span class="co"># full precision, ~32 GB VRAM</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> app.py <span class="at">--mode</span> 2         <span class="co"># NF4 quantization, ~12 GB VRAM</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> app.py <span class="at">--mode</span> 3         <span class="co"># CPU offload + NF4 for low-RAM machines</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>mode 2</code> uses BitsAndBytes’ NF4 quantization on the generation expert weights and keeps the understanding expert at fp16; the quality cost is small for T2I and noticeable but acceptable for free-form editing. The Gradio UI exposes the full set of inference knobs:</p>
<ul>
<li><strong><code>cfg_text_scale</code></strong> — text guidance strength, typical range <strong>4 to 8</strong>. Higher = stronger adherence to the prompt, more saturated outputs.</li>
<li><strong><code>cfg_image_scale</code></strong> — image-condition guidance (used for editing tasks where an input image is supplied), typical range <strong>1 to 2</strong>. Higher = stronger adherence to the input image’s structure.</li>
<li><strong><code>cfg_interval</code></strong> — the <span class="math inline">\(\tau\)</span> range in which classifier-free guidance is active. Default <code>[0.4, 1.0]</code>. Applying CFG only late in the denoising trajectory often improves detail without hurting layout.</li>
<li><strong><code>num_timesteps</code></strong> — number of Euler integration steps. Default <strong>50</strong>. Lower (20–30) for faster previews, higher (75+) for the last 1–2% of quality.</li>
<li><strong><code>timestep_shift</code></strong> — the rectified-flow time reparameterisation knob from Chapter 10. Higher values (4.0+ as used in BAGEL’s CT and SFT stages) put more steps near <span class="math inline">\(\tau = 0\)</span>, which improves global layout; lower values (1.0) put more steps near <span class="math inline">\(\tau = 1\)</span>, which improves fine details.</li>
<li><strong><code>cfg_renorm_type</code></strong> — <code>global</code>, <code>channel</code>, or <code>text_channel</code>. The last variant applies renormalisation only to the text-conditional path, which is the recommended setting for editing tasks where you want the input image preserved.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Recipe for editing tasks.</strong> Set <code>cfg_text_scale = 4</code>, <code>cfg_image_scale = 1.5</code>, <code>cfg_interval = [0.4, 1.0]</code>, <code>cfg_renorm_type = text_channel</code>, <code>num_timesteps = 50</code>. For free-form / conceptual edits, enable the model’s <em>thinking mode</em> — it produces an explicit reasoning trace before generation and consistently improves IntelligentBench scores.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>On thinking mode.</strong> Inspired by DeepSeek-R1, BAGEL was post-trained on chain-of-thought traces that precede image outputs. Enabling thinking mode at inference (<code>--enable_thinking</code> in <code>app.py</code>, or the toggle in the UI) tells the model to emit a brief textual plan before the image. For ambiguous prompts (“design a logo for a coffee shop that feels like a library”) this often raises quality measurably. For literal prompts (“a red apple on a wooden table”) it does not help and slightly slows inference.</p>
</div>
</div>
</section>
<section id="training-bagel" class="level3">
<h3 class="anchored" data-anchor-id="training-bagel">14.9 Training BAGEL</h3>
<p>Training is documented in <code>scripts/train.sh</code> and <code>TRAIN.md</code>. The practical lessons that propagate from the published recipe:</p>
<ul>
<li><strong>Native-resolution batching with sequence packing.</strong> Pack samples to 32K–45K tokens per rank. Mixed native aspect ratios across a batch is what NaViT supports and what the BAGEL data pipeline assumes; do not pre-resize to a fixed shape.</li>
<li><strong>EMA ratio is stage-dependent.</strong> Pre-training and Continued Training use 0.9999 (slow EMA, smooth); SFT uses 0.995 (fast EMA, follows the data more closely). Forgetting this knob is a common cause of poor SFT results.</li>
<li><strong>Constant learning rate</strong> during PT/CT/SFT, not cosine. This is the resumability trick — you can add data and continue training without re-warming the schedule.</li>
<li><strong><span class="math inline">\(\epsilon = 10^{-15}\)</span> in AdamW</strong> to suppress sporadic loss spikes. Inherited from Llama-3.</li>
<li><strong>Diffusion timestep shift goes 1.0 → 4.0</strong> when resolution jumps from PT to CT. Higher resolution means a longer noise trajectory; bumping the shift compensates.</li>
<li><strong>Weight CE:MSE = 0.25:1</strong> is the only loss-balance knob you need; do not try to tune cross-entropy and MSE rates independently.</li>
</ul>
<p>For fine-tuning BAGEL on a domain-specific corpus (which is, increasingly, how people use it), the recipe is: take the public 7B checkpoint, freeze the SigLIP2 encoder + the FLUX VAE, optionally freeze the <em>understanding expert</em> if your domain is purely generative, run a few hundred million tokens of SFT-style training with EMA 0.995 and LR ~ 2.5e-5. This is exactly the same template as fine-tuning any other LLM, and it is what makes BAGEL practical to adapt.</p>
</section>
<section id="what-bagel-teaches-us-about-unified-models" class="level3">
<h3 class="anchored" data-anchor-id="what-bagel-teaches-us-about-unified-models">14.10 What BAGEL teaches us about unified models</h3>
<p>If you take away one architectural lesson from this chapter, it should be the <strong>hard routing wins</strong> result. Throughout this article we have seen the same shape over and over:</p>
<ul>
<li><span class="math inline">\(\pi_0\)</span> separates the VLM backbone and the action expert with disjoint FFN weights, joined by shared self-attention.</li>
<li>BAGEL separates the understanding expert and the generation expert in exactly the same way.</li>
<li>Mixture-of-Experts language models (DeepSeek-V3, Qwen2.5 MoE, Kimi-VL) route different tokens to different FFNs.</li>
<li><span class="math inline">\(\pi_{0.7}\)</span> glues a small image-generation world model onto a VLA in the same modular pattern.</li>
</ul>
<p>The pattern is consistent. Jointly optimising the <em>same</em> parameter slot for two genuinely different objectives — language modelling vs flow matching, semantic understanding vs pixel generation, perception vs action — drives the model into a worse compromise of weight space than separating the slot and sharing the attention. This is the empirical answer to the long-running “should unified models share everything?” debate. They should share <strong>attention</strong>; they should <em>not</em> share <strong>FFNs</strong>.</p>
<p>The second lesson is <strong>emergence is real and scales with data, not parameters alone.</strong> BAGEL’s Intelligent Editing capability does not exist at 1 T tokens; it exists at 4 T tokens. Throwing more parameters at a smaller-data run would not have produced it. The Wei-et-al-2022 emergence story from LLMs replays cleanly in the multimodal setting.</p>
<p>The third lesson is <strong>interleaved data is what unlocks reasoning across modalities.</strong> Text-only pretraining gives you a great language model. Image-text-pair pretraining gives you a great VLM. Image-text-pair pretraining <em>plus</em> large-scale interleaved sequences gives you a model that can plan in language and act in pixels. The video- and web-interleaved corpora are what closed the gap between BAGEL and the proprietary GPT-4o-class systems on world-knowledge generation (the WISE benchmark).</p>
<p>The fourth lesson — the one that loops back to robotics and motivates this entire Part C — is <strong>the same model is now plausibly the backbone of generation, understanding, <em>and</em> embodied reasoning</strong>. <span class="math inline">\(\pi_{0.7}\)</span> uses BAGEL as a world-model component. World-model researchers use VLM understanding scores to benchmark their systems. VLA researchers borrow flow matching from image generation. The boundary between “image generator”, “world model”, and “robot policy” is dissolving. BAGEL is a particularly clear instance of that dissolution, because all three lives could plausibly start from this single set of weights.</p>
</section>
</section>
<section id="chapter-15-putting-it-all-together-a-unified-picture-of-the-modern-ai-stack" class="level2">
<h2 class="anchored" data-anchor-id="chapter-15-putting-it-all-together-a-unified-picture-of-the-modern-ai-stack">Chapter 15 — Putting It All Together: A Unified Picture of the Modern AI Stack</h2>
<p>The point of this article was always synthesis. Three hundred-plus pages of background on transformers, VLMs, VAEs, diffusion, flow matching, VLAs, world models, and unified architectures — and the punchline is that they are all the <em>same machine</em>, with the modalities of the inputs, the loss on the outputs, and the application of the action expert varied. This final chapter says that out loud.</p>
<section id="the-recurring-patterns" class="level3">
<h3 class="anchored" data-anchor-id="the-recurring-patterns">15.1 The recurring patterns</h3>
<p>Look back across the three Parts and the same primitives keep reappearing.</p>
<ul>
<li><strong>The transformer is the universal substrate.</strong> Language modelling, vision encoding, image generation (DiTs), video generation (CausVid), robot action prediction (the <span class="math inline">\(\pi_0\)</span> action expert), world modelling (DreamerV4, V-JEPA 2’s predictor), even self-supervised representation learning (I-JEPA, V-JEPA). The transformer block — multi-head self-attention plus a feed-forward sublayer — is the workhorse of every component we built up. Convolutions have been almost entirely displaced. RNNs are a niche choice. Mamba-class state-space models are an interesting alternative but have not yet taken over any major frontier. Everything is a transformer.</li>
<li><strong>Rectified flow / flow matching is the universal continuous-output loss.</strong> Image generation (SD3, FLUX), video generation (CausVid, Self Forcing), robot actions (<span class="math inline">\(\pi_0\)</span>, <span class="math inline">\(\pi_{0.5}\)</span>), text rendering inside image models (BAGEL), the upcoming wave of audio and 3D models — all converging on the same simple linear-Gaussian flow with the conditional vector field <span class="math inline">\(u(\mathbf{x}^\tau \mid \mathbf{x}) = \mathbf{x} - \epsilon\)</span> that we derived in Chapter 10. The diffusion-vs-flow-matching argument is effectively settled: flow matching with linear paths wins on simplicity, sample quality, and inference speed.</li>
<li><strong>Pretrain, then post-train, then preference-align.</strong> Every modern system uses the same three-phase recipe. Pre-training on noisy diverse data gives the base model its priors. Post-training on small high-quality curated data gives it fluent task execution. Preference / RL polishing handles the last mile. LLMs (Chapter 4). VLMs (Chapter 6). Image models (Chapter 9). VLAs (<span class="math inline">\(\pi_0\)</span> → <span class="math inline">\(\pi_{0.5}\)</span>). World models (V-JEPA 2’s two-stage recipe). All the same shape.</li>
<li><strong>Action chunking, KV caching, MoE-style modality experts, RoPE variants, RMSNorm, SwiGLU.</strong> These are the small parts that show up everywhere. They started in language modelling, propagated to VLMs, then to VLAs, then to unified models. The mechanical reuse is striking — you can read a 2024 image-generation paper and a 2026 robot-foundation-model paper, and the activation function, normalisation, positional encoding, and inference-time KV cache are identical.</li>
</ul>
<p>If you were starting a new modality from scratch in 2026 — say, you wanted to build a foundation model for protein dynamics or surgical-robot force feedback or atomic-force-microscopy traces — the default architecture would now write itself: a transformer with RoPE, RMSNorm, SwiGLU, GQA, two or three modality experts hard-routed by token type, sharing attention; a flow-matching head for continuous outputs and a cross-entropy head for discrete ones; pre-train on whatever scrape you can find, post-train on whatever curated data you can collect, RL-polish at the end. This is the default. It is going to be the default for the rest of the decade.</p>
</section>
<section id="the-great-parallel" class="level3">
<h3 class="anchored" data-anchor-id="the-great-parallel">15.2 The Great Parallel</h3>
<p>Jim Fan’s <em>Great Parallel</em> says that robotics is now following the LLM playbook step for step, and we can see it cleanly when we line up the two timelines.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Stage</th>
<th>Language</th>
<th>Robotics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Generative pre-training</td>
<td>GPT, GPT-2, GPT-3 (2018–2020)</td>
<td>World models — Dreamer, Genie, DreamDojo (2018–2026)</td>
</tr>
<tr class="even">
<td>Capability fine-tuning</td>
<td>InstructGPT, GPT-3.5 (2022)</td>
<td>VLAs — RT-2, OpenVLA, <span class="math inline">\(\pi_0\)</span> (2023–2025)</td>
</tr>
<tr class="odd">
<td>Preference / alignment</td>
<td>ChatGPT, RLHF (2022)</td>
<td><span class="math inline">\(\pi_{0.5}\)</span> open-world, <span class="math inline">\(\pi_{0.6}\)</span> self-improvement (2025)</td>
</tr>
<tr class="even">
<td>Reasoning / planning</td>
<td>o1, DeepSeek-R1 (2024–2025)</td>
<td><span class="math inline">\(\pi_{0.7}\)</span> hybrid VLA + world model (2026)</td>
</tr>
<tr class="odd">
<td>Tool use / agents</td>
<td>(in progress)</td>
<td>(in progress)</td>
</tr>
</tbody>
</table>
<p>The mapping is not metaphorical. The same techniques transfer: chain-of-thought style sub-goal images, RLHF-style self-improvement, mixture-of-experts modality routing. The same scaling laws appear to hold (NVIDIA’s EgoScale paper finds R² = 0.9983 between hours of human video and robot policy performance). The same data-curation problems dominate.</p>
<p>If the parallel keeps holding — and it has held remarkably well for the last three years — then we are roughly at the <strong>GPT-2 moment of physical AI</strong>. The pieces are all in place. The scaling has begun. The dramatic capability jumps are ahead of us, not behind us.</p>
<blockquote class="blockquote">
<p>A useful gut-check: GPT-2 was released in February 2019. ChatGPT was released in November 2022. If the timeline of physical AI is even half as compressed as the language timeline, the embodied equivalent of ChatGPT — a robot foundation model usable by ordinary developers, with broad real-world generalisation — should not feel impossible by 2028.</p>
</blockquote>
</section>
<section id="the-big-open-problems" class="level3">
<h3 class="anchored" data-anchor-id="the-big-open-problems">15.3 The big open problems</h3>
<p>Five problems sit at the frontier as of this writing. Watch them.</p>
<ol type="1">
<li><strong>Long-horizon planning and persistence.</strong> Both VLAs and world models lose coherence within seconds-to-minutes. <span class="math inline">\(\pi_{0.7}\)</span>’s sub-goal-image trick is a hack around this, not a solution. The deep question is how to learn long-range structure when the only signal is per-frame reconstruction or per-step action MSE. This is the embodied analogue of the long-context problem in LLMs.</li>
<li><strong>Touch, force, and proprioception.</strong> Almost every model in this article is <em>vision and language only</em>. Real manipulation lives in contact dynamics. The first foundation model that takes 6-axis force/torque sensing as a first-class modality (not as an afterthought concatenation) is likely a generational leap, and it will not look like a VLM with an extra channel.</li>
<li><strong>Sim-to-real with photorealistic <em>and</em> physically accurate world models.</strong> Current world models are usually one or the other — DreamDojo is photorealistic but not load-bearing on physics; Mujoco is physically accurate but renders like 2008. The model that closes both gaps simultaneously becomes the universal training environment for embodied agents.</li>
<li><strong>JEPA-style abstract latents vs pixel-space dreams.</strong> This is the architectural axis on which the field will probably split for the next two years. Pixel-space world models (Cosmos, DreamDojo) are inspectable and produce decoded video that can be checked by a human; latent-space world models (V-JEPA 2) are 30× faster and refuse to spend capacity on irrelevant pixels. Both bets have champions and capital. The likely outcome is <em>hybrid</em>: latent prediction for planning, pixel generation for visualisation and sim-to-real.</li>
<li><strong>Action conditioning from internet video without action labels.</strong> This is the meta-problem of robotics data. Genie’s latent-action-model trick is the most promising direction so far — infer actions from frame-to-frame deltas, expose them as a control channel. But the resulting action space is opaque and does not align with any particular robot’s joint conventions. Solving the alignment problem — translating a learned latent action into a sequence of motor commands for a <em>specific</em> embodiment — is, plausibly, the single move that would unlock orders-of-magnitude more training data for VLAs and world models alike.</li>
</ol>
</section>
<section id="what-to-read-next" class="level3">
<h3 class="anchored" data-anchor-id="what-to-read-next">15.4 What to read next</h3>
<p>If you got to the end of this article and want to keep going, the references inside the chapters are themselves a curriculum. A loose month-by-month suggestion:</p>
<ul>
<li><strong>Month 1 — solidify the foundations.</strong> Re-read <em>Attention Is All You Need</em> (Vaswani et al., 2017), the GPT-2 paper, the Llama-3 technical report, and the Qwen2.5 report. These are the substrate of everything else.</li>
<li><strong>Month 2 — diffusion and flow matching.</strong> Ho et al.&nbsp;2020 (DDPM), Lipman et al.&nbsp;2022 (flow matching), Liu 2022 (rectified flow), Peebles &amp; Xie 2023 (DiT), Esser et al.&nbsp;2024 (SD3). Most of this article’s continuous-output story is in these five papers.</li>
<li><strong>Month 3 — VLAs.</strong> Brohan et al.&nbsp;2023 (RT-2), Kim et al.&nbsp;2024 (OpenVLA), Black et al.&nbsp;2024 (<span class="math inline">\(\pi_0\)</span>, the one you should read most carefully), Pertsch et al.&nbsp;2025 (<span class="math inline">\(\pi_{0.5}\)</span> open-world). Read the openpi GitHub README and skim the configs.</li>
<li><strong>Month 4 — world models.</strong> Ha &amp; Schmidhuber 2018 (the original), Hafner et al.&nbsp;2025 (DreamerV3 Nature paper), Bruce et al.&nbsp;2024 (Genie), Yang et al.&nbsp;2024 (UniSim), Yin/Huang 2025 (AR-DiT), Huang et al.&nbsp;2025 (Self Forcing), Jang et al.&nbsp;2025 (DreamGen). The Moe Capital essay this chapter has been tracking is the best overview I know.</li>
<li><strong>Month 5 — JEPA and the contrarian bet.</strong> LeCun 2022 (position paper), Assran et al.&nbsp;2023 (I-JEPA), Bardes et al.&nbsp;2024 (V-JEPA), Assran et al.&nbsp;2025 (V-JEPA 2), Balestriero &amp; LeCun 2025 (LeJEPA).</li>
<li><strong>Month 6 — unified models, hands-on.</strong> Read the BAGEL paper end-to-end. Run it. Fine-tune it on a small domain dataset. This is the experiment that will teach you the most about what the rest of the stack feels like in practice.</li>
</ul>
</section>
<section id="closing-thought" class="level3">
<h3 class="anchored" data-anchor-id="closing-thought">15.5 Closing thought</h3>
<p>We started Part A with the smallest unit of meaning a transformer can process — a token. We are ending Part C with a flow-matching head that produces, fifty times a second, a vector of motor commands that fold someone’s laundry; with a video world model that imagines the next frame of a kitchen scene; with an open unified model you can download tonight that draws what it understands and understands what it draws.</p>
<p>The interesting thing is not that we <em>can</em> do these things. It is that we can do them all with essentially <strong>one architecture</strong>, varied at the edges. A transformer. Attention shared across modalities. Modality-specific experts hard-routed by token type. Flow matching on the continuous outputs, cross-entropy on the discrete ones. Pretrain on whatever scrape you can find. Post-train on what you actually care about. Repeat.</p>
<p>It is the most thorough exercise in <em>one tool, every nail</em> that machine learning has ever produced, and it is far from over. There is plenty of nail left.</p>
<p>To borrow Jim Fan’s line one more time: we were born too late to explore the Earth, and too early for the stars. We may have arrived just in time to teach machines how to dream the physical world into existence — and, with a bit of luck and a lot of GPUs, to live inside the dream with them.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/madhaviit\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Madhav Kadam, All Rights Reserved.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/madhaviit" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/kpmadhav18" target="_blank">
      <i class="bi bi-twitter-x" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/madhav-kadam" target="_blank">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>