---
title: "Being Internship Ready"
author: Madhav Kadam
date: 2023-05-11
date-modified: 2023-05-11
slug: audit-1
# image: 
categories: 
  - Talk
  - Seniors
  - Internship
# alias:
#   - /blog/2021-a11y-website/01-wave-audit-1/
subtitle: "Insights seniors told us about internship drive before ours"
excerpt: ""
---

> **What did Seniors advise??**

As I sat with my seniors, they shared their unique perspectives on preparing for interviews. I was reminded of the quote, "The secret of getting ahead is getting started."

Deepkamal, a seasoned ICPC World Finalist in his 4th year, emphasized the significance of Data Structures and Algorithms (DSA) for job placements. He mentioned that Competitive Programming (CP) isn't obligatory but stressed the utmost importance of DSA. He advised against any form of cheating and suggested using Leetcode as the best approach to excel. Additionally, he highlighted the importance of a strong grasp of Database Management Systems (DBMS) and recommended Interviewbit as a well-structured preparation platform. He cautioned against falling for the trap of paid courses and suggested that 30 days are adequate for Interviewbit preparation.

Jainil recommends focusing on writing clean and precise code and emphasizes the importance of algorithms for machine learning enthusiasts. He suggests not immediately looking for a solution when you're a beginner and recommends spending a maximum of an hour on a problem as you progress. He also advises against doing competitive programming just for the sake of it and stresses the importance of being able to explain your solutions in interviews. Jainil also suggests preparing well for database management systems, object-oriented programming, and being able to explain your projects and introductions. He recommends focusing on the "why" factor in projects. Additionally, Jainil advises against copying projects and suggests preparing a questionnaire in case you face tough questions during an interview.


Kushan was really into certificates and preferred paper and research internships over corporate jobs. He had a published paper with Nagendra Sir and a strong GRE score. He recommended focusing on strong SOP and LOR for Masters and having a good CPI.


Sruthi stressed having some dream companies as they keep up your motivation. Satya Bhaiya, who happens to be the placement manager from the CSE department, coordinated this discussion. He also explained how to prepare a good CV and resume.
From my year, Mihir Patel had doubts about consulting and was looking at ISB as an option. As the conversation progressed, the importance of mock interviews and solving puzzles in Interview-bit became apparent. Sound basics of C/C++ also seemed to be a crucial skill. All the seniors thoroughly answered my doubts regarding R&D roles. They advised ML enthusiasts, "You can start working in startups or go for a research internship."


Listening to these bright minds and their journey, the ups and downs they have gone through, I could not help but think of the famous quote - "The only impossible journey is the one you never begin." These words echoed in my mind as I left the session after a photograph with all the seniors, ready to start preparing for my own interviews.

Since my notes were very brief, I used ChatGPT to curate this blog. You can also find this blog on [medium](https://madhavkadam.medium.com/ready-for-internship-drive-b2a54a32d954)