---
title:  <span class="hindi-kalam">स्वच्छ भारतासाठी मी काय करू शकतो?</span>
author: Madhav Kadam
date: 2018-02-10
date-modified: 2018-02-10
slug: audit-1
# image: 
categories: 
  - Opinion
  - Thought
# mainfont: Kalam
# alias:
#   - /blog/2021-a11y-website/01-wave-audit-1/

---
<div class="hindi-kalam">

'निर्मलं सदा सुंदरम् ।' 

आज आपण आधुनिक युगात जगत आहोत. ए.पी.जे. अब्दुल कलाम यांनी दाखवलेले भारताला जागतिक महासत्ता बनविण्याचे स्वप्न साकार करायचे असेल तर प्रत्येक भारतीयाने स्वतः पासून स्वच्छतेस सुरूवात करणे क्रमप्राप्त ठरते. दुसरा काय करतो यापेक्षा मी काय करतो महत्त्वाचे ! म्हणून, मी व्यक्तिगत स्वच्छतेबरोबरच माझे घर व घराभोवतालच्या परिसराच्या स्वच्छतेस प्राधान्य देईन. याकरिता, माझ्या गल्लीतील आणि प्रभागातील जनतेस स्वच्छतेचे महत्त्व पटवून देईन.

मी माझ्या घरातील केरकचरा, घनकचरा, रद्दी आणि ई-वेस्ट यांची योग्य ती विल्हेवाट लावीन. यासाठी प्लास्टिकचा वापर करणार नाही. शक्य तितका ओला कचरा शेतामध्ये गाडून त्यापासून पर्यावरणपूरक सेंद्रिय खताची निर्मिती करीन. माझ्या घरगुती वापरातून बाहेर पडणारे पाणी भूमिगतरीत्या ड्रेनेजमध्ये सोडीन व मार्गात ते पाणी कोठेही तुंबणार नाही याची काळजी घेईन. आपण आपल्या प्रत्येक कृतीतून काहीना काही निर्माण होतच असते. मग आपण आपल्या कृतीतून स्वच्छताच का नाही निर्माण करायची?

मी शाळेत असताना कागदाची कपटे कचराकुंडीतच टाकेन. मी शाळेचा परिसर स्वच्छ ठेवीन व यासाठी मित्रांची मदत घेईन. अविघटनशीन पदार्थांच्या बाबतीत 'Reduce-Reuse-Recycle' या त्रिसूत्रीचा वापर करीन. 'स्वच्छतेतून समृद्धीकडे' हा विचार लक्षात घेऊन मी स्वच्छता अभियान माझ्या पातळीवर राबवीन. 'टाकाऊ पासून टिकाऊ' या मूलमंत्राचा अंगीकार करीन. आपल्या धार्मिक परंपरा जोपासतानाही परिसर अस्वच्छ होऊ देणार नाही. असे म्हणतात की 'Cleanliness is next to godliness.' हीच स्वच्छता जीवनात अंगीकारून जीवन सुंदर बनायला हवे.

२ ऑक्टोबर २०१९ रोजी महात्मा गांधीची १५०वी जयंती आहे. या पार्श्वभूमीवर २ ऑक्टोबर २०१४ रोजी 'स्वच्छ भारत अभियान' सुरू करण्यात आले आहे. यात प्रत्येक भारतीयाने सहभागी व्हावे. मी फक्त २ ऑक्टोबर रोजीच नाही तर पूर्ण वर्षभर स्वच्छतेसाठी व्रतस्थ राहीन. भारताला स्वच्छ व सुंदर बनवण्यात शक्य तितके योगदान देईन. कारण, 'I had become and I will remain a part & parcel of स्वच्छ भारत मिशन.' चला तर मग भारताला स्वच्छ व सुंदर बनवूया...

<br>
</div>