---
title: "How to manage Academics in CSE engineering?"
author: Madhav Kadam
date: 2024-07-25
date-modified: 2024-07-25
slug: audit-1
# image: 
categories: 
  - Opinion
  - Thought
# alias:
#   - /blog/2021-a11y-website/01-wave-audit-1/
subtitle: "My learnings from first 3 years of undergraduate studies in Computer Science"
excerpt: "पटलं तर घ्या"
---



> **Academics in CSE engineering**



One thing we either care too much about or we don’t care at all about is CGPA/CPI. Some say it has nothing to do with real work/ skills required out there in the world, some say one day before exam is all you need, some say it’s really important that if you regularly attend the classes and make good notes, you are good to go. All these are true up to some extent. Here is real picture what I have observed in last 6 semesters of my CSE Engineering.

So, most of the colleges start first year with a weird combo of everything, you like it or not (Situation may change with NEP). We like PCM when we study for Competitive exams because those are essentially oriented to challenge our mind logically but all engineering disciplines are not exactly as logical as what JEE was. There is theory, there is research then there are faculty biases and weird advices from seniors. So, many (including me) discard these subjects in our first year as useless and ruminate how bad our education system is. Now though your argument might not be flawed but to make it work you might need to go through a lengthy official channel so your juniors might benefit. But now you have at your hand, these subjects like Chemistry, ~~Physics~~ ,etc. {You know I love physics} Study these like you studied NCERT chapter from which certainly one or two questions pop and nobody (not really) likes to study them. Study only once well in advance before exam and just give a quick revision before exam, see and solve all PYQs twice (if faculty is in continuity). Study the Math as thoroughly as you can. Give economics a good shot at studying. Give good hand at programming as its essential to develop problem solving. Don’t fall prey to fear mongering of societies to induct you due to peer pressure. Sure try hard to get into top-notch technical clubs that have good track record (Cynaptics Club of IIT Indore😁). First year vacation go for God level CP/ internships (not ones on cheap sites.. networking is all you need (with fair assumption that you will nurture skills) to land a first year internship at good companies). Alas these details and many other things in some other md some other time. 

One more thing, I started using Tablet in my third year for taking notes, and it doesn’t really makes a difference except it makes it easier to share your notes with your friends or not so friends. Having course maps, in which you just make graphs depicting what chapters, topics, sub-topics are taught, is really helpful in covering entire syllabus for exams and also helps you retrieve right concepts required for answering questions. If you feel slides are enough and if you are attending classes, just write day date and what were Headings in the lecture, will suffice to retain lot of things.  Some profs have bias for good handwriting and good presentation in answer sheet ( Something to incorporate if you have luxury to do so). Having a study group is not at all essential but it helps while preparing for exams. One most important thing, don’t panic in exam if you feel you have not studied well since you can take cues from question but to do that you need open and calm brain. Manage sleep cycle well during exams (if you are prepared already, else burn your midnight oil but cover the material). Make sure to breakfast if you have exams in morning or have light lunch 2 hours before exam, if exam is in afternoon session. Reach exam hall on time, settle and cool down. Breathe slowly to gain composure. These are very basic things that our moms tell every exam day, but most of us live in hostels, so thought of mentioning these.

Let’s move to Second and third year now, here you start with core subjects from CSE. Some of these course include DSA, DBMS, Automata (or TOC as is called), Discrete math, Computer Architecture(🥹), Software Engineering, Computer Networks, Operating Systems, Parallel Computing, ML, CV, Computational Intelligence, Optimization algorithms. Now, one thing all these course will offer you is good base especially if your university conducts good Labs associated with them. These courses are pretty standard and you can study them on your own if you wish. But what I have felt is attending few classes is certainly going to help you in terms of content. Either make your own notes, if slides are not provided, or have a good Note maker good-friend (As I was for many in my class). Why notes matter because profs are likely to teach, speak something not on slides with specific intention of putting these things in exam. If attendance carry marks, don’t miss classes please. Some courses are so damn scoring that attendance will decide final grade. If particular professor is known for strict (many call it vindictive) grading, attend all classes of such courses. PYQs are GODS for these courses. Just, make sure to solve (or study answers from instructor answer manual ) of exercises in the recommended textbook. It always helps those who solve (and ruins those who don’t💀). Now, how much and when is totally dependent on your priorities. I prefer having weekly reviews (despite you attend classes or not) to avoid last minute panic and a general sense of what is going on in course. Do labs seriously, complete the exercises then and there, don’t wait for deadlines, do labs on your own (unless you are sure that there will be no lab exam and you have all the answers readymade from senior and you hate that subject). These are highly scoring courses. I have friends who have done way lot more things than me and managed to get near full grades. Also there are friends who have pursued everything from fun, joy and memorable experiences, bunked classes and still managed to do pretty good (🤘).  Look definition of good is not same for everyone. But good academics mostly will make your way smoother and easier in whatever domain you see yourself going. Be it job market or be it research/ higher education. These two years are also stepping stones in transforming yourself into a skilled individual. So there is much more than academics in these two year and make sure you succeed there. Use all kind of tricks to save time from acads and to invest in yourself from solving CP questions / network / ~~read my blogs~~ in class which is ultimately disappointing or in a useless(for you) lab. Make sure to not get into unnecessary conflict with any prof / TAs.

<br>

This blog is written without any help from GenAI models.