---
title: <span class="hindi-kalam">मोहन</span>
toc: false
# sidebar: false
--- 
  <div class="hindi-kalam" onmousedown='return false;' onselectstart="return false;" oncopy="return false;" onpaste="return false;" oncut="return false;"><!-- # मोहन -->

वर्षों तक जग में घूम-घूम 

वियोग विघ्नों को चूम चूम 

सह अब शब्द अपमान प्रखर

मोहन आया कुछ और निखर
<br>


सौहार्द की राह बताने को 

सबको एक साथ लाने को 

अंग्रेजों को समझाने को 

और भारत से हटवाने को 

गांधीजी वापस भारत आए 

सत्याग्रह की महारथ लाए

<br>



संभाले संग्राम की डोर चले

पकड़े अहिंसा की छोर चले

तिलक गोखले साथ थे

सर पर भारत मां के हाथ थे
<br>




अंग्रेज चाहे नील उगाना

और असंगत कर भराना 

चंपारण में पहुंचे गांधी 

उठाव की जो लाई आंधी 

अंग्रेजों को रुकना पड़ा 

निवासियों सामने झुकना पड़ा 

<br>


खिलाफत की रमजान मनाई

रामराज्य की याद दिलाई 

डायर ने जब जीवन जलाया 

गांधी ने असहयोग चलाया 

अपनों को भी बहुत सुनाया 

स्वराज का सपना आगे बढ़ाया

उपोषण किया स्वदेशी चलाया

प्रेम एवं सत्य का रास्ता दिखाया
<br>


गांधी ने हुंकार किया 

सविनय अवज्ञा का प्रचार किया

दांडी मार्च पर चले गांधी 

संपूर्ण स्वराज बोले गांधी 

<br>



गोलमेज का मेल चला 

तोड़ो हुकूमत करो का खेल चला

जेल में उपवास चलाया 

मंदिरों में छुआछूत जलाया 

<br>

छोड़ो भारत की साख दिखाई 

करो या मरो की आंख दिखाई 

अंग्रेजों और अब सह ना सके 

अखंड भारत की राह ले ना सके 

सांप्रदायिकता की आग लगा के 

भाई को भाई से भीड़ा के 

किसी का सपना साकार हुआ 

गांधी का मन निराकार हुआ 

<br>






सब कुछ छोड़ने चले गांधी 

समाज को जोड़ने चले गांधी 

कट्टर पंथियों को अब जाग आई 

गांधी के निषेध की मांग आई

हितवचन इन्हें न समझ आया 

राम के उपासक को रावण बताया 

गांधी के विचार को मारने चले 

जो असाध्य था साधने चले 

युवा हत्यारे 78 साल के बूढ़े से डर गए 

राम का नाम लेते-लेते गांधी मारे नहीं अमर हो गए

<br>

-अविक्षित नचिकेत

</div>



